//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalUnitOfWork.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDepartmentGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimDepartmentGroup()
        {
            this.DimDepartmentGroup1 = new HashSet<DimDepartmentGroup>();
            this.FactFinance = new HashSet<FactFinance>();
        }
    
        public int DepartmentGroupKey { get; set; }
        public Nullable<int> ParentDepartmentGroupKey { get; set; }
        public string DepartmentGroupName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimDepartmentGroup> DimDepartmentGroup1 { get; set; }
        public virtual DimDepartmentGroup DimDepartmentGroup2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactFinance> FactFinance { get; set; }
    }
}
