//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalUnitOfWork.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimReseller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimReseller()
        {
            this.FactResellerSales = new HashSet<FactResellerSales>();
            this.FactResellerSalesXL_CCI = new HashSet<FactResellerSalesXL_CCI>();
            this.FactResellerSalesXL_PageCompressed = new HashSet<FactResellerSalesXL_PageCompressed>();
        }
    
        public int ResellerKey { get; set; }
        public Nullable<int> GeographyKey { get; set; }
        public string ResellerAlternateKey { get; set; }
        public string Phone { get; set; }
        public string BusinessType { get; set; }
        public string ResellerName { get; set; }
        public Nullable<int> NumberEmployees { get; set; }
        public string OrderFrequency { get; set; }
        public Nullable<byte> OrderMonth { get; set; }
        public Nullable<int> FirstOrderYear { get; set; }
        public Nullable<int> LastOrderYear { get; set; }
        public string ProductLine { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public Nullable<decimal> AnnualSales { get; set; }
        public string BankName { get; set; }
        public Nullable<byte> MinPaymentType { get; set; }
        public Nullable<decimal> MinPaymentAmount { get; set; }
        public Nullable<decimal> AnnualRevenue { get; set; }
        public Nullable<int> YearOpened { get; set; }
    
        public virtual DimGeography DimGeography { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactResellerSales> FactResellerSales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactResellerSalesXL_CCI> FactResellerSalesXL_CCI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactResellerSalesXL_PageCompressed> FactResellerSalesXL_PageCompressed { get; set; }
    }
}
