//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalUnitOfWork.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactFinance
    {
        public int FinanceKey { get; set; }
        public int DateKey { get; set; }
        public int OrganizationKey { get; set; }
        public int DepartmentGroupKey { get; set; }
        public int ScenarioKey { get; set; }
        public int AccountKey { get; set; }
        public double Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual DimAccount DimAccount { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimDepartmentGroup DimDepartmentGroup { get; set; }
        public virtual DimOrganization DimOrganization { get; set; }
        public virtual DimScenario DimScenario { get; set; }
    }
}
