//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalUnitOfWork.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDMPrep
    {
        public string EnglishProductCategoryName { get; set; }
        public string Model { get; set; }
        public int CustomerKey { get; set; }
        public string Region { get; set; }
        public Nullable<int> Age { get; set; }
        public string IncomeGroup { get; set; }
        public short CalendarYear { get; set; }
        public short FiscalYear { get; set; }
        public byte Month { get; set; }
        public string OrderNumber { get; set; }
        public byte LineNumber { get; set; }
        public short Quantity { get; set; }
        public decimal Amount { get; set; }
    }
}
