//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubliPayments.ServiceReferenceExpedienteDigital {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModeloRespuestaExpediente", Namespace="http://schemas.datacontract.org/2004/07/wsExpedientesDigitales")]
    [System.SerializableAttribute()]
    public partial class ModeloRespuestaExpediente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CréditoField;
        
        private int EstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoField;
        
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioRespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Crédito {
            get {
                return this.CréditoField;
            }
            set {
                if ((object.ReferenceEquals(this.CréditoField, value) != true)) {
                    this.CréditoField = value;
                    this.RaisePropertyChanged("Crédito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Estatus {
            get {
                return this.EstatusField;
            }
            set {
                if ((this.EstatusField.Equals(value) != true)) {
                    this.EstatusField = value;
                    this.RaisePropertyChanged("Estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motivo {
            get {
                return this.MotivoField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoField, value) != true)) {
                    this.MotivoField = value;
                    this.RaisePropertyChanged("Motivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioRespuesta {
            get {
                return this.UsuarioRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioRespuestaField, value) != true)) {
                    this.UsuarioRespuestaField = value;
                    this.RaisePropertyChanged("UsuarioRespuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModeloGuardarExpediente", Namespace="http://schemas.datacontract.org/2004/07/wsExpedientesDigitales")]
    [System.SerializableAttribute()]
    public partial class ModeloGuardarExpediente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CreditoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdEntidadFinancieraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomArchivoField;
        
        private string NombreAcreditadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Credito {
            get {
                return this.CreditoField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditoField, value) != true)) {
                    this.CreditoField = value;
                    this.RaisePropertyChanged("Credito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdEntidadFinanciera {
            get {
                return this.IdEntidadFinancieraField;
            }
            set {
                if ((object.ReferenceEquals(this.IdEntidadFinancieraField, value) != true)) {
                    this.IdEntidadFinancieraField = value;
                    this.RaisePropertyChanged("IdEntidadFinanciera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomArchivo {
            get {
                return this.NomArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomArchivoField, value) != true)) {
                    this.NomArchivoField = value;
                    this.RaisePropertyChanged("NomArchivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string NombreAcreditado {
            get {
                return this.NombreAcreditadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreAcreditadoField, value) != true)) {
                    this.NombreAcreditadoField = value;
                    this.RaisePropertyChanged("NombreAcreditado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruta {
            get {
                return this.RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaField, value) != true)) {
                    this.RutaField = value;
                    this.RaisePropertyChanged("Ruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/wsExpedientesDigitales")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PubliPayments.ServiceReferenceExpedienteDigital.ModeloRespuestaExpediente))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PubliPayments.ServiceReferenceExpedienteDigital.ModeloGuardarExpediente))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Detalle {
            get {
                return this.DetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleField, value) != true)) {
                    this.DetalleField = value;
                    this.RaisePropertyChanged("Detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceExpedienteDigital.IExpedienteDigital")]
    public interface IExpedienteDigital {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpedienteDigital/RespuestaExpediente", ReplyAction="http://tempuri.org/IExpedienteDigital/RespuestaExpedienteResponse")]
        string RespuestaExpediente(PubliPayments.ServiceReferenceExpedienteDigital.ModeloRespuestaExpediente modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpedienteDigital/RespuestaExpediente", ReplyAction="http://tempuri.org/IExpedienteDigital/RespuestaExpedienteResponse")]
        System.Threading.Tasks.Task<string> RespuestaExpedienteAsync(PubliPayments.ServiceReferenceExpedienteDigital.ModeloRespuestaExpediente modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpedienteDigital/GuardarExpediente", ReplyAction="http://tempuri.org/IExpedienteDigital/GuardarExpedienteResponse")]
        PubliPayments.ServiceReferenceExpedienteDigital.Response GuardarExpediente(PubliPayments.ServiceReferenceExpedienteDigital.ModeloGuardarExpediente modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpedienteDigital/GuardarExpediente", ReplyAction="http://tempuri.org/IExpedienteDigital/GuardarExpedienteResponse")]
        System.Threading.Tasks.Task<PubliPayments.ServiceReferenceExpedienteDigital.Response> GuardarExpedienteAsync(PubliPayments.ServiceReferenceExpedienteDigital.ModeloGuardarExpediente modelo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExpedienteDigitalChannel : PubliPayments.ServiceReferenceExpedienteDigital.IExpedienteDigital, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExpedienteDigitalClient : System.ServiceModel.ClientBase<PubliPayments.ServiceReferenceExpedienteDigital.IExpedienteDigital>, PubliPayments.ServiceReferenceExpedienteDigital.IExpedienteDigital {
        
        public ExpedienteDigitalClient() {
        }
        
        public ExpedienteDigitalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExpedienteDigitalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpedienteDigitalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpedienteDigitalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RespuestaExpediente(PubliPayments.ServiceReferenceExpedienteDigital.ModeloRespuestaExpediente modelo) {
            return base.Channel.RespuestaExpediente(modelo);
        }
        
        public System.Threading.Tasks.Task<string> RespuestaExpedienteAsync(PubliPayments.ServiceReferenceExpedienteDigital.ModeloRespuestaExpediente modelo) {
            return base.Channel.RespuestaExpedienteAsync(modelo);
        }
        
        public PubliPayments.ServiceReferenceExpedienteDigital.Response GuardarExpediente(PubliPayments.ServiceReferenceExpedienteDigital.ModeloGuardarExpediente modelo) {
            return base.Channel.GuardarExpediente(modelo);
        }
        
        public System.Threading.Tasks.Task<PubliPayments.ServiceReferenceExpedienteDigital.Response> GuardarExpedienteAsync(PubliPayments.ServiceReferenceExpedienteDigital.ModeloGuardarExpediente modelo) {
            return base.Channel.GuardarExpedienteAsync(modelo);
        }
    }
}
