//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOB.SPF.ConecII.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotificationMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GOB.SPF.ConecII.Web.Resources.NotificationMessage", typeof(NotificationMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clasificación de factor @ correctamente.
        /// </summary>
        internal static string ClasificacionFactorActiveSuccess {
            get {
                return ResourceManager.GetString("ClasificacionFactorActiveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clasificación de factor guardada correctamente..
        /// </summary>
        internal static string ClasificacionFactorInsertSuccess {
            get {
                return ResourceManager.GetString("ClasificacionFactorInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clasificación de factor modificada correctamente..
        /// </summary>
        internal static string ClasificacionFactorUpdateSuccess {
            get {
                return ResourceManager.GetString("ClasificacionFactorUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuota está @ correctamente..
        /// </summary>
        internal static string CuotasActiveSuccess {
            get {
                return ResourceManager.GetString("CuotasActiveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuota ha sido guardada correctamente..
        /// </summary>
        internal static string CuotasInsertSuccess {
            get {
                return ResourceManager.GetString("CuotasInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuota ha sido modificada correctamente..
        /// </summary>
        internal static string CuotasUpdateSuccess {
            get {
                return ResourceManager.GetString("CuotasUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuota ha sido validada correctamente..
        /// </summary>
        internal static string CuotasValidationSuccess {
            get {
                return ResourceManager.GetString("CuotasValidationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadena de Dependencia @ correctamente.
        /// </summary>
        internal static string DependenciaActiveSuccess {
            get {
                return ResourceManager.GetString("DependenciaActiveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadena de dependencia guardada correctamente..
        /// </summary>
        internal static string DependenciaInsertSuccess {
            get {
                return ResourceManager.GetString("DependenciaInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadena de dependencia modificada correctamente..
        /// </summary>
        internal static string DependenciaUpdateSuccess {
            get {
                return ResourceManager.GetString("DependenciaUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to División está @ correctamente..
        /// </summary>
        internal static string DivisionActiveSuccess {
            get {
                return ResourceManager.GetString("DivisionActiveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La división se ha guardado correctamente..
        /// </summary>
        internal static string DivisionInsertSuccess {
            get {
                return ResourceManager.GetString("DivisionInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to División modificado correctamente..
        /// </summary>
        internal static string DivisionUpdateSuccess {
            get {
                return ResourceManager.GetString("DivisionUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activada.
        /// </summary>
        internal static string Estatus_Row_Active {
            get {
                return ResourceManager.GetString("Estatus_Row_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to desactivada.
        /// </summary>
        internal static string Estatus_Row_Inactive {
            get {
                return ResourceManager.GetString("Estatus_Row_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor @ correctamente..
        /// </summary>
        internal static string FactorActiveSuccess {
            get {
                return ResourceManager.GetString("FactorActiveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor entidad federativa guardado correctamente..
        /// </summary>
        internal static string FactorEntidadFederativaInsertSuccess {
            get {
                return ResourceManager.GetString("FactorEntidadFederativaInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor entidad federativa modificado correctamente..
        /// </summary>
        internal static string FactorEntidadFederativaUpdateSuccess {
            get {
                return ResourceManager.GetString("FactorEntidadFederativaUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor validado correctamente.
        /// </summary>
        internal static string FactorInsertSuccess {
            get {
                return ResourceManager.GetString("FactorInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor de Ley de ingresos @ correctamente..
        /// </summary>
        internal static string FactorLeyIngresoActiveSuccess {
            get {
                return ResourceManager.GetString("FactorLeyIngresoActiveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor de ley de ingresos guardado correctamente..
        /// </summary>
        internal static string FactorLeyIngresoInsertSuccess {
            get {
                return ResourceManager.GetString("FactorLeyIngresoInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor de ley de ingresos modificado correctamente..
        /// </summary>
        internal static string FactorLeyIngresoUpdateSuccess {
            get {
                return ResourceManager.GetString("FactorLeyIngresoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor modificado correctamente..
        /// </summary>
        internal static string FactorUpdateSuccess {
            get {
                return ResourceManager.GetString("FactorUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de que desea @ la fracción seleccionada?.
        /// </summary>
        internal static string FraccionActiveQuestion {
            get {
                return ResourceManager.GetString("FraccionActiveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracción está @ correctamente.
        /// </summary>
        internal static string FraccionActiveSuccess {
            get {
                return ResourceManager.GetString("FraccionActiveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracción guardada correctamente..
        /// </summary>
        internal static string FraccionInsertSuccess {
            get {
                return ResourceManager.GetString("FraccionInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de modificar la fracción?.
        /// </summary>
        internal static string FraccionUpdateQuestion {
            get {
                return ResourceManager.GetString("FraccionUpdateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracción modificada correctamente..
        /// </summary>
        internal static string FraccionUpdateSuccess {
            get {
                return ResourceManager.GetString("FraccionUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto @ correctamente.
        /// </summary>
        internal static string GastosInherentesActiveSuccess {
            get {
                return ResourceManager.GetString("GastosInherentesActiveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto de gasto inherente guardado correctamente..
        /// </summary>
        internal static string GastosInherentesInsertSuccess {
            get {
                return ResourceManager.GetString("GastosInherentesInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto de gasto inherente modificado correctamente..
        /// </summary>
        internal static string GastosInherentesUpdateSuccess {
            get {
                return ResourceManager.GetString("GastosInherentesUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El grupo ha sido @ correctamente.
        /// </summary>
        internal static string GrupoActiveSuccess {
            get {
                return ResourceManager.GetString("GrupoActiveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El grupo ha sido guardado exitosamente..
        /// </summary>
        internal static string GrupoInsertSuccess {
            get {
                return ResourceManager.GetString("GrupoInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El grupo ha sido modificado correctamente..
        /// </summary>
        internal static string GrupoUpdateSuccess {
            get {
                return ResourceManager.GetString("GrupoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo @ correctamente..
        /// </summary>
        internal static string PeriodoActiveSuccess {
            get {
                return ResourceManager.GetString("PeriodoActiveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo guardado correctamente..
        /// </summary>
        internal static string PeriodoInsertSuccess {
            get {
                return ResourceManager.GetString("PeriodoInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo modificado correctamente..
        /// </summary>
        internal static string PeriodoUpdateSuccess {
            get {
                return ResourceManager.GetString("PeriodoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave de Referencia @ correctamente..
        /// </summary>
        internal static string ReferenciaActiveSuccess {
            get {
                return ResourceManager.GetString("ReferenciaActiveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave de referencia guardada correctamente..
        /// </summary>
        internal static string ReferenciaInsertSuccess {
            get {
                return ResourceManager.GetString("ReferenciaInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave de referencia modificada correctamente..
        /// </summary>
        internal static string ReferenciaUpdateSuccess {
            get {
                return ResourceManager.GetString("ReferenciaUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Documento @ correctamente..
        /// </summary>
        internal static string TipoDocumentoActiveSuccess {
            get {
                return ResourceManager.GetString("TipoDocumentoActiveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento guardado correctamente..
        /// </summary>
        internal static string TipoDocumentoInsertSuccess {
            get {
                return ResourceManager.GetString("TipoDocumentoInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento modificado correctamente..
        /// </summary>
        internal static string TipoDocumentoUpdateSuccess {
            get {
                return ResourceManager.GetString("TipoDocumentoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de servicio @ correctamente..
        /// </summary>
        internal static string TipoServicioActiveSuccess {
            get {
                return ResourceManager.GetString("TipoServicioActiveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de servicio guardado correctamente..
        /// </summary>
        internal static string TipoServicioInsertSuccess {
            get {
                return ResourceManager.GetString("TipoServicioInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de servicio modificado correctamente..
        /// </summary>
        internal static string TipoServicioUpdateSuccess {
            get {
                return ResourceManager.GetString("TipoServicioUpdateSuccess", resourceCulture);
            }
        }
    }
}
