//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsBroxel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BroxelCommonEntities : DbContext
    {
        public BroxelCommonEntities()
            : base("name=BroxelCommonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CatFuncionalidades> CatFuncionalidades { get; set; }
        public DbSet<CatFuncionalidadesXInfoClientes> CatFuncionalidadesXInfoClientes { get; set; }
        public DbSet<InfoClientes> InfoClientes { get; set; }
        public DbSet<RelacionIDsReplicado> RelacionIDsReplicado { get; set; }
        public DbSet<AccionesTarjetaAsociada> AccionesTarjetaAsociada { get; set; }
        public DbSet<ConfigTarjetaAsociada> ConfigTarjetaAsociada { get; set; }
        public DbSet<ControlsCuentaAsociada> ControlsCuentaAsociada { get; set; }
        public DbSet<EstatusCuentaAsociada> EstatusCuentaAsociada { get; set; }
        public DbSet<Producto> Producto { get; set; }
        public DbSet<CuentaAsociadaFamily> CuentaAsociadaFamily { get; set; }
        public DbSet<CuentaPadreFamily> CuentaPadreFamily { get; set; }
        public DbSet<MaquilaReplica> Maquila { get; set; }
    }
}
