//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsBroxel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciudadesCredencial
    {
        public long Id { get; set; }
        public int IdEstado { get; set; }
        public string CodigoCiudad { get; set; }
        public string Ciudad { get; set; }
        public string CodigoEstado { get; set; }
    }
}
