//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsBroxel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigTarjetaAsociada
    {
        public int Id { get; set; }
        public int IdCuentaAsociada { get; set; }
        public int IdAccionTarjeta { get; set; }
        public bool Estatus { get; set; }
    
        public virtual AccionesTarjetaAsociada AccionesTarjetaAsociada { get; set; }
        public virtual CuentaAsociadaFamily CuentaAsociadaFamily { get; set; }
    }
}
