//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsBroxel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaPadreFamily
    {
        public CuentaPadreFamily()
        {
            this.CuentaAsociadaFamily = new HashSet<CuentaAsociadaFamily>();
        }
    
        public int Id { get; set; }
        public string ClaveCliente { get; set; }
        public string NumeroCuenta { get; set; }
        public Nullable<int> IdUsuarioOnlineBroxel { get; set; }
    
        public virtual ICollection<CuentaAsociadaFamily> CuentaAsociadaFamily { get; set; }
    }
}
