//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsBroxel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaAsociadaFamily
    {
        public CuentaAsociadaFamily()
        {
            this.ConfigTarjetaAsociada = new HashSet<ConfigTarjetaAsociada>();
            this.ControlsCuentaAsociada = new HashSet<ControlsCuentaAsociada>();
        }
    
        public int Id { get; set; }
        public string NumeroCuenta { get; set; }
        public int IdCuentaPadre { get; set; }
        public int IdEstatusCuenta { get; set; }
        public Nullable<bool> EstaConfirmada { get; set; }
    
        public virtual ICollection<ConfigTarjetaAsociada> ConfigTarjetaAsociada { get; set; }
        public virtual ICollection<ControlsCuentaAsociada> ControlsCuentaAsociada { get; set; }
        public virtual CuentaPadreFamily CuentaPadreFamily { get; set; }
        public virtual EstatusCuentaAsociada EstatusCuentaAsociada { get; set; }
    }
}
