//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsBroxel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisposicionesEfectivo
    {
        public long Id { get; set; }
        public Nullable<int> IdTransferencia { get; set; }
        public string NumCuenta { get; set; }
        public string NumTarjeta { get; set; }
        public string ClabeDestino { get; set; }
        public Nullable<double> Monto { get; set; }
        public string CuentaSTP { get; set; }
        public string ReferenciaPago { get; set; }
        public string ClaveRastreo { get; set; }
        public string StatusPago { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string Motivo { get; set; }
        public Nullable<int> EnvioPago { get; set; }
        public Nullable<float> DispPOSAntes { get; set; }
        public Nullable<float> DispPOSDespues { get; set; }
        public Nullable<System.DateTime> FechaHoraCreacion { get; set; }
        public int GeneraComision { get; set; }
    }
}
