//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsBroxel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dispersionesInternas
    {
        public long id { get; set; }
        public string idSolicitud { get; set; }
        public string cuenta { get; set; }
        public string tarjeta { get; set; }
        public string cvc { get; set; }
        public string fechaExpiracion { get; set; }
        public Nullable<double> incrementoPOS { get; set; }
        public Nullable<double> incrementoATM { get; set; }
        public string codigoRespuestaPOS { get; set; }
        public string codigoAutorizacionPOS { get; set; }
        public string idmovPOS { get; set; }
        public Nullable<double> antesPOS { get; set; }
        public Nullable<double> despuesPOS { get; set; }
        public string codigoRespuestaATM { get; set; }
        public string codigoAutorizacionATM { get; set; }
        public string idmovATM { get; set; }
        public Nullable<double> antesATM { get; set; }
        public Nullable<double> despuesATM { get; set; }
        public string codRespAnulPOS { get; set; }
        public string idAnulPOS { get; set; }
        public string codAutAnulPOS { get; set; }
        public Nullable<double> antesAnulPOS { get; set; }
        public Nullable<double> despuesAnulPOS { get; set; }
        public string codRespAnulATM { get; set; }
        public string idAnulATM { get; set; }
        public string codAutAnulATM { get; set; }
        public Nullable<double> antesAnulATM { get; set; }
        public Nullable<double> despuesAnulATM { get; set; }
        public string producto { get; set; }
        public string claveCliente { get; set; }
        public bool bloquearCuenta { get; set; }
    }
}
