//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsBroxel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoClientes
    {
        public InfoClientes()
        {
            this.CatFuncionalidadesXInfoClientes = new HashSet<CatFuncionalidadesXInfoClientes>();
        }
    
        public int IdInfoClientes { get; set; }
        public string ClaveCliente { get; set; }
        public string Producto { get; set; }
    
        public virtual ICollection<CatFuncionalidadesXInfoClientes> CatFuncionalidadesXInfoClientes { get; set; }
    }
}
