//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsBroxel
{
    using System;
    using System.Collections.Generic;
    
    public partial class logCorreoDispersion
    {
        public int id { get; set; }
        public string from { get; set; }
        public string to { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public string fromPassword { get; set; }
        public string fromName { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<int> status { get; set; }
        public string error { get; set; }
    }
}
