//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsBroxel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogUsuariosOnlineBroxel
    {
        public long Id { get; set; }
        public string Ip { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Accion { get; set; }
        public string Extra { get; set; }
        public string Sitio { get; set; }
        public int tipoLogin { get; set; }
    }
}
