//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsBroxel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobile_session
    {
        public int id { get; set; }
        public int idUserSecure { get; set; }
        public int idUser { get; set; }
        public System.DateTime creacion { get; set; }
        public System.DateTime vigencia { get; set; }
        public sbyte estatus { get; set; }
    }
}
