//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsBroxel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelacionIDsReplicado
    {
        public long Id { get; set; }
        public long IdTablaOrigen { get; set; }
        public long IdOrigen { get; set; }
        public string TablaDestino { get; set; }
        public long IdDestino { get; set; }
    }
}
