//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsBroxel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetasFisicasAdicionales
    {
        public long Id { get; set; }
        public long IdUsuarioOnlineBroxel { get; set; }
        public string Tarjeta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string NumCuenta { get; set; }
        public string CodigoProducto { get; set; }
        public int TipoIngreso { get; set; }
        public bool Activo { get; set; }
        public string Alias { get; set; }
    }
}
