//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsBroxel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetasBroxelLayout
    {
        public int id { get; set; }
        public int idApp { get; set; }
        public string usuarioCreacion { get; set; }
        public string estado { get; set; }
        public string codigoProducto { get; set; }
        public string codigoServicio { get; set; }
        public string marcaTpp { get; set; }
        public string grupoLiquidacion { get; set; }
        public string habilitaCompra { get; set; }
        public string usuarioGenera { get; set; }
        public Nullable<decimal> porcBonificacion { get; set; }
        public string codigoPeriodoBonificacion { get; set; }
        public string cantidadCuotasBonificacion { get; set; }
    }
}
