//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOB.SPF.ConecII.AccessData.Schemas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfiguracionServicios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfiguracionServicios() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GOB.SPF.ConecII.AccessData.Schemas.ConfiguracionServicios", typeof(ConfiguracionServicios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConfiguracionServicioActualizarConfiguraciones {
            get {
                return ResourceManager.GetString("ConfiguracionServicioActualizarConfiguraciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuracion.sp_ConfiguracionTipoServicioAreaObtenerPorIdTipoServicioIdArea.
        /// </summary>
        internal static string ConfiguracionServicioAreaObtenerIdTipoServicioIdArea {
            get {
                return ResourceManager.GetString("ConfiguracionServicioAreaObtenerIdTipoServicioIdArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuracion.sp_OtinerConfiguracionServicoDetalle.
        /// </summary>
        internal static string ConfiguracionServicioDetalle {
            get {
                return ResourceManager.GetString("ConfiguracionServicioDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuracion.sp_InsertaConfServicio.
        /// </summary>
        internal static string ConfiguracionServicioInsertarConfiguraciones {
            get {
                return ResourceManager.GetString("ConfiguracionServicioInsertarConfiguraciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuracion.sp_ConfServicioObtenerPorIdTipoServicioIdCentroCosto.
        /// </summary>
        internal static string ConfiguracionServicioObtenerIdTipoServicioIdCentroCosto {
            get {
                return ResourceManager.GetString("ConfiguracionServicioObtenerIdTipoServicioIdCentroCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuracion.sp_ConfServicioObtenerPorIdConfiguracion.
        /// </summary>
        internal static string ConfiguracionServicioObtenerPorIdConfServicio {
            get {
                return ResourceManager.GetString("ConfiguracionServicioObtenerPorIdConfServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuracion.sp_ConfServicioObtenerPorPaginado.
        /// </summary>
        internal static string ConfiguracionServicioObtenerTodosPaginados {
            get {
                return ResourceManager.GetString("ConfiguracionServicioObtenerTodosPaginados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Tabla.
        /// </summary>
        internal static string ConfiguracionServicioParametro01InsertarConf {
            get {
                return ResourceManager.GetString("ConfiguracionServicioParametro01InsertarConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuracion.ConfiguracionServicio.
        /// </summary>
        internal static string ConfiguracionServicioTipoTablaUsuario {
            get {
                return ResourceManager.GetString("ConfiguracionServicioTipoTablaUsuario", resourceCulture);
            }
        }
    }
}
