//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunCorp.DataAccessSqlServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using SunCorp.Entities;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SunCorpEntities : DbContext
    {
        public SunCorpEntities()
            : base("name=SunCorpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConContacto> ConContacto { get; set; }
        public virtual DbSet<DirCatColonia> DirCatColonia { get; set; }
        public virtual DbSet<DirCatEstado> DirCatEstado { get; set; }
        public virtual DbSet<DirCatMunicipio> DirCatMunicipio { get; set; }
        public virtual DbSet<DirCatTipoAsentamiento> DirCatTipoAsentamiento { get; set; }
        public virtual DbSet<DirCatTipoZona> DirCatTipoZona { get; set; }
        public virtual DbSet<DirDirecciones> DirDirecciones { get; set; }
        public virtual DbSet<OpCatEstadosNas> OpCatEstadosNas { get; set; }
        public virtual DbSet<OpCatTipoEstadoNas> OpCatTipoEstadoNas { get; set; }
        public virtual DbSet<OpEstadosPorUsuarios> OpEstadosPorUsuarios { get; set; }
        public virtual DbSet<ProArchivos> ProArchivos { get; set; }
        public virtual DbSet<ProArchivosPorProductos> ProArchivosPorProductos { get; set; }
        public virtual DbSet<ProCatMarca> ProCatMarca { get; set; }
        public virtual DbSet<ProCatModelo> ProCatModelo { get; set; }
        public virtual DbSet<ProDiviciones> ProDiviciones { get; set; }
        public virtual DbSet<ProFamilias> ProFamilias { get; set; }
        public virtual DbSet<ProProducto> ProProducto { get; set; }
        public virtual DbSet<ProVendedor> ProVendedor { get; set; }
        public virtual DbSet<ProVendedorTienda> ProVendedorTienda { get; set; }
        public virtual DbSet<SisArbolMenu> SisArbolMenu { get; set; }
        public virtual DbSet<SisTipoUsuarioPorMenu> SisTipoUsuarioPorMenu { get; set; }
        public virtual DbSet<TieSucursal> TieSucursal { get; set; }
        public virtual DbSet<TieTienda> TieTienda { get; set; }
        public virtual DbSet<UsEstatusUsuario> UsEstatusUsuario { get; set; }
        public virtual DbSet<UsTipoUsuario> UsTipoUsuario { get; set; }
        public virtual DbSet<UsUsuarioPorZona> UsUsuarioPorZona { get; set; }
        public virtual DbSet<UsUsuarios> UsUsuarios { get; set; }
        public virtual DbSet<UsZona> UsZona { get; set; }
        public virtual DbSet<UsZonaPorEstado> UsZonaPorEstado { get; set; }
    
        public virtual ObjectResult<Usp_GetListCatalogsSystem_Result> Usp_GetListCatalogsSystem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetListCatalogsSystem_Result>("Usp_GetListCatalogsSystem");
        }
    
        public virtual ObjectResult<Usp_GetListUsZona_Result> Usp_GetListUsZona(Nullable<int> i_Page_Index, Nullable<int> i_Page_Count, ObjectParameter o_total_rows)
        {
            var i_Page_IndexParameter = i_Page_Index.HasValue ?
                new ObjectParameter("i_Page_Index", i_Page_Index) :
                new ObjectParameter("i_Page_Index", typeof(int));
    
            var i_Page_CountParameter = i_Page_Count.HasValue ?
                new ObjectParameter("i_Page_Count", i_Page_Count) :
                new ObjectParameter("i_Page_Count", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetListUsZona_Result>("Usp_GetListUsZona", i_Page_IndexParameter, i_Page_CountParameter, o_total_rows);
        }
    }
}
