//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunCorp.Entities
{
    
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract]
    public partial class DirCatEstado
    
    {
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DirCatEstado()
        {
            this.DirCatColonia = new HashSet<DirCatColonia>();
            this.DirDirecciones = new HashSet<DirDirecciones>();
            this.UsZonaPorEstado = new HashSet<UsZonaPorEstado>();
        }
    
    	[DataMember]
        public int IdEstado { get; set; }
    
    	[DataMember]
        public string NombreEstado { get; set; }
    
    	[DataMember]
        public string NombreOficial { get; set; }
    
    	[DataMember]
        public string Creador { get; set; }
    
    	[DataMember]
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
    	[DataMember]
        public string ModificadoPor { get; set; }
    
    	[DataMember]
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
    	[DataMember]
        public Nullable<bool> Borrado { get; set; }
    
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DirCatColonia> DirCatColonia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DirDirecciones> DirDirecciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsZonaPorEstado> UsZonaPorEstado { get; set; }
    }
}
