//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunCorp.Entities
{
    
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract]
    public partial class TieSucursal
    
    {
    
    	[DataMember]
        public int IdSucursal { get; set; }
    
    	[DataMember]
        public Nullable<int> IdZona { get; set; }
    
    	[DataMember]
        public Nullable<int> IdContacto { get; set; }
    
    	[DataMember]
        public Nullable<int> IdDirecciones { get; set; }
    
    	[DataMember]
        public Nullable<int> IdTienda { get; set; }
    
    	[DataMember]
        public string NombreTienda { get; set; }
    
    	[DataMember]
        public string NombreGerente { get; set; }
    
    	[DataMember]
        public string Comentarios { get; set; }
    
    	[DataMember]
        public Nullable<bool> Borrado { get; set; }
    
    	[DataMember]
        public Nullable<int> Activo { get; set; }
    
    	[DataMember]
        public string NoSucursal { get; set; }
    
    
        public virtual ConContacto ConContacto { get; set; }
        public virtual DirDirecciones DirDirecciones { get; set; }
        public virtual TieTienda TieTienda { get; set; }
        public virtual UsZona UsZona { get; set; }
    }
}
