//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunCorp.Entities
{
    
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract]
    public partial class TieTienda
    
    {
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TieTienda()
        {
            this.ProVendedorTienda = new HashSet<ProVendedorTienda>();
            this.TieSucursal = new HashSet<TieSucursal>();
        }
    
    	[DataMember]
        public int IdTienda { get; set; }
    
    	[DataMember]
        public Nullable<int> IdDireccion { get; set; }
    
    	[DataMember]
        public Nullable<int> IdContacto { get; set; }
    
    	[DataMember]
        public string NombreTienda { get; set; }
    
    	[DataMember]
        public string NombreResponsable { get; set; }
    
    	[DataMember]
        public Nullable<System.DateTime> FechaAlta { get; set; }
    
    	[DataMember]
        public Nullable<bool> Activo { get; set; }
    
    	[DataMember]
        public Nullable<bool> Borrado { get; set; }
    
    
        public virtual ConContacto ConContacto { get; set; }
        public virtual DirDirecciones DirDirecciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProVendedorTienda> ProVendedorTienda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TieSucursal> TieSucursal { get; set; }
    }
}
