//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunCorp.Entities
{
    
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract]
    public partial class UsTipoUsuario
    
    {
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsTipoUsuario()
        {
            this.OpEstadosPorUsuarios = new HashSet<OpEstadosPorUsuarios>();
            this.SisTipoUsuarioPorMenu = new HashSet<SisTipoUsuarioPorMenu>();
            this.UsUsuarios = new HashSet<UsUsuarios>();
        }
    
    	[DataMember]
        public int IdTipoUsuario { get; set; }
    
    	[DataMember]
        public string TipoUsuario { get; set; }
    
    	[DataMember]
        public string Descripcion { get; set; }
    
    	[DataMember]
        public bool Borrado { get; set; }
    
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpEstadosPorUsuarios> OpEstadosPorUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SisTipoUsuarioPorMenu> SisTipoUsuarioPorMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsUsuarios> UsUsuarios { get; set; }
    }
}
