//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunCorp.Entities
{
    
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract]
    public partial class UsUsuarioPorZona
    
    {
    
    	[DataMember]
        public int IdUsuarioZona { get; set; }
    
    	[DataMember]
        public Nullable<int> IdZona { get; set; }
    
    	[DataMember]
        public Nullable<int> IdUsuarios { get; set; }
    
    
        public virtual UsUsuarios UsUsuarios { get; set; }
        public virtual UsZona UsZona { get; set; }
    }
}
