//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOB.SPF.ConecII.AccessData.Schemas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Solicitud {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Solicitud() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GOB.SPF.ConecII.AccessData.Schemas.Solicitud", typeof(Solicitud).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_ClienteActualizar.
        /// </summary>
        internal static string ClienteActualizar {
            get {
                return ResourceManager.GetString("ClienteActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_DomicilioFiscalActualizar.
        /// </summary>
        internal static string ClienteActualizarDomicilioFiscal {
            get {
                return ResourceManager.GetString("ClienteActualizarDomicilioFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_ClienteCambiarEstatus.
        /// </summary>
        internal static string ClienteCambiarEstatus {
            get {
                return ResourceManager.GetString("ClienteCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_ClienteInsertar.
        /// </summary>
        internal static string ClienteInsertar {
            get {
                return ResourceManager.GetString("ClienteInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_ClienteObtenerDomicilioFiscal.
        /// </summary>
        internal static string ClienteObtenerDomicilioFiscal {
            get {
                return ResourceManager.GetString("ClienteObtenerDomicilioFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_ClienteObtenerPorCriterio.
        /// </summary>
        internal static string ClienteObtenerPorCriterio {
            get {
                return ResourceManager.GetString("ClienteObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_ClienteObtenerPorId.
        /// </summary>
        internal static string ClienteObtenerPorId {
            get {
                return ResourceManager.GetString("ClienteObtenerPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_ClienteObtenerPorNombreCorto.
        /// </summary>
        internal static string ClienteObtenerPorNombreCorto {
            get {
                return ResourceManager.GetString("ClienteObtenerPorNombreCorto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_ClienteObtenerPorRazonSocial.
        /// </summary>
        internal static string ClienteObtenerPorRazonSocial {
            get {
                return ResourceManager.GetString("ClienteObtenerPorRazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_ClienteObtener.
        /// </summary>
        internal static string ClienteObtenerTodos {
            get {
                return ResourceManager.GetString("ClienteObtenerTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_ClienteValidar.
        /// </summary>
        internal static string ClienteValidar {
            get {
                return ResourceManager.GetString("ClienteValidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_DomicilioFiscalInsertar.
        /// </summary>
        internal static string ClientInsertarDomicilioFiscal {
            get {
                return ResourceManager.GetString("ClientInsertarDomicilioFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_CorreoExternoActualizar.
        /// </summary>
        internal static string CorreoExternoActualizar {
            get {
                return ResourceManager.GetString("CorreoExternoActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_CorreoExternoInsertar.
        /// </summary>
        internal static string CorreoExternoInsertar {
            get {
                return ResourceManager.GetString("CorreoExternoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_CorreoExternoObtenerPorId.
        /// </summary>
        internal static string CorreoObtenerPorIdExterno {
            get {
                return ResourceManager.GetString("CorreoObtenerPorIdExterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_CorreoInstalacionObtenerPorId.
        /// </summary>
        internal static string CorreoObtenerPorIdInstalacion {
            get {
                return ResourceManager.GetString("CorreoObtenerPorIdInstalacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_ExternoActualizar.
        /// </summary>
        internal static string ExternoActualizar {
            get {
                return ResourceManager.GetString("ExternoActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_ExternoInsertar.
        /// </summary>
        internal static string ExternoInsertar {
            get {
                return ResourceManager.GetString("ExternoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_ExternoObtenerPorId.
        /// </summary>
        internal static string ExternoObtenerPorId {
            get {
                return ResourceManager.GetString("ExternoObtenerPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_InstalacionActualizar.
        /// </summary>
        internal static string InstalacionActualizar {
            get {
                return ResourceManager.GetString("InstalacionActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_InstalacionCambiarEstatus.
        /// </summary>
        internal static string InstalacionCambiarEstatus {
            get {
                return ResourceManager.GetString("InstalacionCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_InstalacionInsertar.
        /// </summary>
        internal static string InstalacionInsertar {
            get {
                return ResourceManager.GetString("InstalacionInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_InstalacionObtener.
        /// </summary>
        internal static string InstalacionObtener {
            get {
                return ResourceManager.GetString("InstalacionObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_InstalacionObtenerPorCriterio.
        /// </summary>
        internal static string InstalacionObtenerPorCriterio {
            get {
                return ResourceManager.GetString("InstalacionObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_InstalacionObtenerPorId.
        /// </summary>
        internal static string InstalacionObtenerPorId {
            get {
                return ResourceManager.GetString("InstalacionObtenerPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_SolicitudesObtener.
        /// </summary>
        internal static string SolicitudesObtener {
            get {
                return ResourceManager.GetString("SolicitudesObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_SolicitudesObtenerPorCriterio.
        /// </summary>
        internal static string SolicitudesObtenerPorCriterio {
            get {
                return ResourceManager.GetString("SolicitudesObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_SolicitudesObtenerPorId.
        /// </summary>
        internal static string SolicitudesObtenerPorId {
            get {
                return ResourceManager.GetString("SolicitudesObtenerPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_TelefonoExternoActualizar.
        /// </summary>
        internal static string TelefonoExternoActualizar {
            get {
                return ResourceManager.GetString("TelefonoExternoActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_TelefonoExternoInsertar.
        /// </summary>
        internal static string TelefonoExternoInsertar {
            get {
                return ResourceManager.GetString("TelefonoExternoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_TelefonosExternoObtenerPorId.
        /// </summary>
        internal static string TelefonoObtenerPorIdExterno {
            get {
                return ResourceManager.GetString("TelefonoObtenerPorIdExterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.sp_TelefonosInstalacionObtenerPorId.
        /// </summary>
        internal static string TelefonoObtenerPorIdInstalacion {
            get {
                return ResourceManager.GetString("TelefonoObtenerPorIdInstalacion", resourceCulture);
            }
        }
    }
}
