//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOB.SPF.ConecII.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MethodApiSolicitud {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MethodApiSolicitud() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GOB.SPF.ConecII.Web.Resources.MethodApiSolicitud", typeof(MethodApiSolicitud).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente/CambiarEstatus.
        /// </summary>
        internal static string ClienteCambiarEstatus {
            get {
                return ResourceManager.GetString("ClienteCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente/ObtenerDomicilioFiscal.
        /// </summary>
        internal static string ClienteDomicilioFiscalObtener {
            get {
                return ResourceManager.GetString("ClienteDomicilioFiscalObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente/Guardar.
        /// </summary>
        internal static string ClienteGuardar {
            get {
                return ResourceManager.GetString("ClienteGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente/ObtenerPorCriterio.
        /// </summary>
        internal static string ClienteObtenerPorCriterio {
            get {
                return ResourceManager.GetString("ClienteObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente/ObtenerPorId.
        /// </summary>
        internal static string ClienteObtenerPorId {
            get {
                return ResourceManager.GetString("ClienteObtenerPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente/ObtenerTodos.
        /// </summary>
        internal static string ClientesObtener {
            get {
                return ResourceManager.GetString("ClientesObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instalacion/CambiarEstatus.
        /// </summary>
        internal static string InstalacionCambiarEstatus {
            get {
                return ResourceManager.GetString("InstalacionCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instalacion/ObtenerPorCriterio.
        /// </summary>
        internal static string InstalacionObtenerPorCriterio {
            get {
                return ResourceManager.GetString("InstalacionObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instalacion/ObtenerPorId.
        /// </summary>
        internal static string InstalacionObtenerPorId {
            get {
                return ResourceManager.GetString("InstalacionObtenerPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instalacion/ObtenerTodos.
        /// </summary>
        internal static string InstalacionObtenerTodos {
            get {
                return ResourceManager.GetString("InstalacionObtenerTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instalacion/Save.
        /// </summary>
        internal static string InstalacionSave {
            get {
                return ResourceManager.GetString("InstalacionSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente/ObtenerTodosPorNombreCorto.
        /// </summary>
        internal static string ObtenerTodosPorNombreCorto {
            get {
                return ResourceManager.GetString("ObtenerTodosPorNombreCorto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente/ObtenerTodosPorRazonSocial.
        /// </summary>
        internal static string ObtenerTodosPorRazonSocial {
            get {
                return ResourceManager.GetString("ObtenerTodosPorRazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitante/ObtenerTodos.
        /// </summary>
        internal static string SolicitantesObtener {
            get {
                return ResourceManager.GetString("SolicitantesObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitudes/Obtener.
        /// </summary>
        internal static string SolicitudesObtener {
            get {
                return ResourceManager.GetString("SolicitudesObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitudes/ObtenerPorCriterio.
        /// </summary>
        internal static string SolicitudesObtenerPorCriterio {
            get {
                return ResourceManager.GetString("SolicitudesObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitudes/ObtenerId.
        /// </summary>
        internal static string SolicitudesObtenerPorId {
            get {
                return ResourceManager.GetString("SolicitudesObtenerPorId", resourceCulture);
            }
        }
    }
}
