//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOB.SPF.ConecII.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MethodApiCatalog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MethodApiCatalog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GOB.SPF.ConecII.Web.Resources.MethodApiCatalog", typeof(MethodApiCatalog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades/ObtenerTodos.
        /// </summary>
        internal static string ActividadObtener {
            get {
                return ResourceManager.GetString("ActividadObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades/ObtenerPorCriterio.
        /// </summary>
        internal static string ActividadObtenerPorCriterio {
            get {
                return ResourceManager.GetString("ActividadObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anios/ObtenerTodos.
        /// </summary>
        internal static string AnioObtener {
            get {
                return ResourceManager.GetString("AnioObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas/ObtenerTodos.
        /// </summary>
        internal static string AreaObtener {
            get {
                return ResourceManager.GetString("AreaObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas/ObtenerPorCriterio.
        /// </summary>
        internal static string AreaObtenerPorCriterio {
            get {
                return ResourceManager.GetString("AreaObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asentamientos/ObtenerTodos.
        /// </summary>
        internal static string AsentamientosObtener {
            get {
                return ResourceManager.GetString("AsentamientosObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClasificacionFactor/CambiarEstatus.
        /// </summary>
        internal static string ClasificacionFactorCambiarEstatus {
            get {
                return ResourceManager.GetString("ClasificacionFactorCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClasificacionFactor/Save.
        /// </summary>
        internal static string ClasificacionFactorGuardar {
            get {
                return ResourceManager.GetString("ClasificacionFactorGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClasificacionFactor/ObtenerTodos.
        /// </summary>
        internal static string ClasificacionFactorObtener {
            get {
                return ResourceManager.GetString("ClasificacionFactorObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClasificacionFactor/ObtenerPorCriterio.
        /// </summary>
        internal static string ClasificacionFactorObtenerPorCriterio {
            get {
                return ResourceManager.GetString("ClasificacionFactorObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigServ/DetalleConfiguracion.
        /// </summary>
        internal static string ConfiguracionDetalle {
            get {
                return ResourceManager.GetString("ConfiguracionDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigServ/InsertarConfiguraciones.
        /// </summary>
        internal static string ConfiguracionServicioInsertarConfiguraciones {
            get {
                return ResourceManager.GetString("ConfiguracionServicioInsertarConfiguraciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigServ/ObtenerTodoPaginado.
        /// </summary>
        internal static string ConfiguracionServicioObtenerPaginado {
            get {
                return ResourceManager.GetString("ConfiguracionServicioObtenerPaginado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigServ/ObtenerPorId.
        /// </summary>
        internal static string ConfiguracionServicioObtenerPorId {
            get {
                return ResourceManager.GetString("ConfiguracionServicioObtenerPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigServ/ObtenerPorIdTipoServicioIdCentroCosto.
        /// </summary>
        internal static string ConfiguracionServicioObtenerPorIdTipoServicioIdCentroCosto {
            get {
                return ResourceManager.GetString("ConfiguracionServicioObtenerPorIdTipoServicioIdCentroCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controles/CambiarEstatus.
        /// </summary>
        internal static string ControlesActualizar {
            get {
                return ResourceManager.GetString("ControlesActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controles/Save.
        /// </summary>
        internal static string ControlesGuardar {
            get {
                return ResourceManager.GetString("ControlesGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controles/ObtenerTodos.
        /// </summary>
        internal static string ControlesObtener {
            get {
                return ResourceManager.GetString("ControlesObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controles/ObtenerListado.
        /// </summary>
        internal static string ControlesObtenerListado {
            get {
                return ResourceManager.GetString("ControlesObtenerListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controles/ObtenerPorCriterio.
        /// </summary>
        internal static string ControlesObtenerPorCriterio {
            get {
                return ResourceManager.GetString("ControlesObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuotas/CambiarEstatus.
        /// </summary>
        internal static string CuotaCambiarEstatus {
            get {
                return ResourceManager.GetString("CuotaCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuotas/Save.
        /// </summary>
        internal static string CuotaGuardar {
            get {
                return ResourceManager.GetString("CuotaGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuotas/ObtenerTodos.
        /// </summary>
        internal static string CuotaObtener {
            get {
                return ResourceManager.GetString("CuotaObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuotas/ObtenerTodosAnos.
        /// </summary>
        internal static string CuotaObtenerAnos {
            get {
                return ResourceManager.GetString("CuotaObtenerAnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuotas/ObtenerPorCriterio.
        /// </summary>
        internal static string CuotaObtenerPorCriterio {
            get {
                return ResourceManager.GetString("CuotaObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogo.sp_CuotasObtenerPorCriterioAnos.
        /// </summary>
        internal static string CuotasObtenerPorCriterioAnos {
            get {
                return ResourceManager.GetString("CuotasObtenerPorCriterioAnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencias/CambiarEstatus.
        /// </summary>
        internal static string DependenciaCambiarEstatus {
            get {
                return ResourceManager.GetString("DependenciaCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencias/Save.
        /// </summary>
        internal static string DependenciaGuardar {
            get {
                return ResourceManager.GetString("DependenciaGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencias/ObtenerTodos.
        /// </summary>
        internal static string DependenciaObtener {
            get {
                return ResourceManager.GetString("DependenciaObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencias/ObtenerPorCriterio.
        /// </summary>
        internal static string DependenciaObtenerPorCriterio {
            get {
                return ResourceManager.GetString("DependenciaObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisiones/CambiarEstatus.
        /// </summary>
        internal static string DivisionesActualizar {
            get {
                return ResourceManager.GetString("DivisionesActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisiones/Save.
        /// </summary>
        internal static string DivisionesGuardar {
            get {
                return ResourceManager.GetString("DivisionesGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisiones/ObtenerTodos.
        /// </summary>
        internal static string DivisionesObtener {
            get {
                return ResourceManager.GetString("DivisionesObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisiones/ObtenerListado.
        /// </summary>
        internal static string DivisionesObtenerListado {
            get {
                return ResourceManager.GetString("DivisionesObtenerListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisiones/ObtenerPorCriterio.
        /// </summary>
        internal static string DivisionesObtenerPorCriterio {
            get {
                return ResourceManager.GetString("DivisionesObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estados/ObtenerTodos.
        /// </summary>
        internal static string EstadoObtener {
            get {
                return ResourceManager.GetString("EstadoObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factores/CambiarEstatus.
        /// </summary>
        internal static string FactorCambiarEstatus {
            get {
                return ResourceManager.GetString("FactorCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresEntidadFederativa/CambiarEstatus.
        /// </summary>
        internal static string FactorEntidadFederativaCambiarEstatus {
            get {
                return ResourceManager.GetString("FactorEntidadFederativaCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactorEntidadFederativa/Obtener/.
        /// </summary>
        internal static string FactorEntidadFederativaDTOObtener {
            get {
                return ResourceManager.GetString("FactorEntidadFederativaDTOObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresEntidadFederativa/ObtenerEstados.
        /// </summary>
        internal static string FactorEntidadFederativaDTOObtenerEstados {
            get {
                return ResourceManager.GetString("FactorEntidadFederativaDTOObtenerEstados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factores/ObtenerFactorPorClasificacion.
        /// </summary>
        internal static string FactorEntidadFederativaDTOObtenerFactor {
            get {
                return ResourceManager.GetString("FactorEntidadFederativaDTOObtenerFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresEntidadFederativa/Save.
        /// </summary>
        internal static string FactorEntidadFederativaGuardar {
            get {
                return ResourceManager.GetString("FactorEntidadFederativaGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresEntidadFederativa/ObtenerTodos.
        /// </summary>
        internal static string FactorEntidadFederativaObtener {
            get {
                return ResourceManager.GetString("FactorEntidadFederativaObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresEntidadFederativa/ObtenerAgrupados.
        /// </summary>
        internal static string FactorEntidadFederativaObtenerAgrupados {
            get {
                return ResourceManager.GetString("FactorEntidadFederativaObtenerAgrupados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresEntidadFederativa/ObtenerPorCriterio.
        /// </summary>
        internal static string FactorEntidadFederativaObtenerPorCriterio {
            get {
                return ResourceManager.GetString("FactorEntidadFederativaObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactorEntidadFederativa/ObtenerSinAgrupar.
        /// </summary>
        internal static string FactorEntidadFederativaSinAgrupar {
            get {
                return ResourceManager.GetString("FactorEntidadFederativaSinAgrupar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresActividadEconomica/ObtenerAgrupados.
        /// </summary>
        internal static string FactoresActividadEconomicaAgrupados {
            get {
                return ResourceManager.GetString("FactoresActividadEconomicaAgrupados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresActividadEconomica/ObtenerPorCriterio.
        /// </summary>
        internal static string FactoresActividadEconomicaObtenerPorCriterio {
            get {
                return ResourceManager.GetString("FactoresActividadEconomicaObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresActividadEconomica/ObtenerTodos.
        /// </summary>
        internal static string FactoresActividadEconomicaObtenerTodos {
            get {
                return ResourceManager.GetString("FactoresActividadEconomicaObtenerTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresActividadEconomica/Save.
        /// </summary>
        internal static string FactoresActividadEconomicaSave {
            get {
                return ResourceManager.GetString("FactoresActividadEconomicaSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresActividadEconomica/ObtenerSinAgrupar.
        /// </summary>
        internal static string FactoresActividadEconomicaSinAgrupar {
            get {
                return ResourceManager.GetString("FactoresActividadEconomicaSinAgrupar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresMunicipio/Obtener.
        /// </summary>
        internal static string FactoresMunicipioObtener {
            get {
                return ResourceManager.GetString("FactoresMunicipioObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresMunicipio/ObtenerPorCriterio.
        /// </summary>
        internal static string FactoresMunicipioObtenerPorCriterio {
            get {
                return ResourceManager.GetString("FactoresMunicipioObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresMunicipio/ObtenerTodos.
        /// </summary>
        internal static string FactoresMunicipioObtenerTodos {
            get {
                return ResourceManager.GetString("FactoresMunicipioObtenerTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factores/Save.
        /// </summary>
        internal static string FactorGuardar {
            get {
                return ResourceManager.GetString("FactorGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresLeyIngreso/CambiarEstatus.
        /// </summary>
        internal static string FactorLeyIngresoCambiarEstatus {
            get {
                return ResourceManager.GetString("FactorLeyIngresoCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresLeyIngreso/Save.
        /// </summary>
        internal static string FactorLeyIngresoGuardar {
            get {
                return ResourceManager.GetString("FactorLeyIngresoGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresLeyIngreso/ObtenerTodos.
        /// </summary>
        internal static string FactorLeyIngresoObtener {
            get {
                return ResourceManager.GetString("FactorLeyIngresoObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresLeyIngreso/ObtenerPorCriterio.
        /// </summary>
        internal static string FactorLeyIngresoObtenerPorCriterio {
            get {
                return ResourceManager.GetString("FactorLeyIngresoObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresMunicipio/Save.
        /// </summary>
        internal static string FactorMunicipioGuardar {
            get {
                return ResourceManager.GetString("FactorMunicipioGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresMunicipios/ObtenerMunicipios.
        /// </summary>
        internal static string FactorMunicipiosDTOObtenerMunicipios {
            get {
                return ResourceManager.GetString("FactorMunicipiosDTOObtenerMunicipios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factores/ObtenerTodos.
        /// </summary>
        internal static string FactorObtener {
            get {
                return ResourceManager.GetString("FactorObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factores/FactorObtenerPorClasificacion.
        /// </summary>
        internal static string FactorObtenerPorClasificacion {
            get {
                return ResourceManager.GetString("FactorObtenerPorClasificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factores/ObtenerPorCriterio.
        /// </summary>
        internal static string FactorObtenerPorCriterio {
            get {
                return ResourceManager.GetString("FactorObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fases/ObtenerTodos.
        /// </summary>
        internal static string FasesObtener {
            get {
                return ResourceManager.GetString("FasesObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fases/ObtenerPorCriterio.
        /// </summary>
        internal static string FasesObtenerPorCriterio {
            get {
                return ResourceManager.GetString("FasesObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracciones/CambiarEstatus.
        /// </summary>
        internal static string FraccionesCambiarEstatus {
            get {
                return ResourceManager.GetString("FraccionesCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracciones/Save.
        /// </summary>
        internal static string FraccionesGuardar {
            get {
                return ResourceManager.GetString("FraccionesGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracciones/ObtenerTodos.
        /// </summary>
        internal static string FraccionesObtener {
            get {
                return ResourceManager.GetString("FraccionesObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracciones/ObtenerPorCriterio.
        /// </summary>
        internal static string FraccionesObtenerPorCriterio {
            get {
                return ResourceManager.GetString("FraccionesObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracciones/ValidarRegistro.
        /// </summary>
        internal static string FraccionValidar {
            get {
                return ResourceManager.GetString("FraccionValidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GastosInherentes/CambiarEstatus.
        /// </summary>
        internal static string GastosInherenteCambiarEstatus {
            get {
                return ResourceManager.GetString("GastosInherenteCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GastosInherentes/Save.
        /// </summary>
        internal static string GastosInherenteGuardar {
            get {
                return ResourceManager.GetString("GastosInherenteGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GastosInherentes/ObtenerTodos.
        /// </summary>
        internal static string GastosInherenteObtener {
            get {
                return ResourceManager.GetString("GastosInherenteObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GastosInherentes/ObtenerPorCriterio.
        /// </summary>
        internal static string GastosInherenteObtenerPorCriterio {
            get {
                return ResourceManager.GetString("GastosInherenteObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo/CambiarEstatus.
        /// </summary>
        internal static string GrupoActualizar {
            get {
                return ResourceManager.GetString("GrupoActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo/Save.
        /// </summary>
        internal static string GrupoGuardar {
            get {
                return ResourceManager.GetString("GrupoGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo/ObtenerTodos.
        /// </summary>
        internal static string GrupoObtener {
            get {
                return ResourceManager.GetString("GrupoObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo/ObtenerPorCriterio.
        /// </summary>
        internal static string GrupoObtenerPorCriterio {
            get {
                return ResourceManager.GetString("GrupoObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos/ObtenerIdDivision/.
        /// </summary>
        internal static string GrupoObtenerPorIdDivision {
            get {
                return ResourceManager.GetString("GrupoObtenerPorIdDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrupoTarifarios/CambiarEstatus.
        /// </summary>
        internal static string GrupoTarifariosCambiarEstatus {
            get {
                return ResourceManager.GetString("GrupoTarifariosCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrupoTarifarios/Save.
        /// </summary>
        internal static string GrupoTarifariosGuardar {
            get {
                return ResourceManager.GetString("GrupoTarifariosGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GruposTarifario/ObtenerTodos.
        /// </summary>
        internal static string GrupoTarifariosObtener {
            get {
                return ResourceManager.GetString("GrupoTarifariosObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrupoTarifarios/ObtenerPorCriterio.
        /// </summary>
        internal static string GrupoTarifariosObtenerPorCriterio {
            get {
                return ResourceManager.GetString("GrupoTarifariosObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrantes/ObtenerTodos.
        /// </summary>
        internal static string IntegrantesObtener {
            get {
                return ResourceManager.GetString("IntegrantesObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrantes/ObtenerPorCriterio.
        /// </summary>
        internal static string IntegrantesObtenerPorCriterio {
            get {
                return ResourceManager.GetString("IntegrantesObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeraquias/CambiarEstatus.
        /// </summary>
        internal static string JeraquiasCambiarEstatus {
            get {
                return ResourceManager.GetString("JeraquiasCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeraquias/Save.
        /// </summary>
        internal static string JeraquiasGuardar {
            get {
                return ResourceManager.GetString("JeraquiasGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerarquias/ObtenerTodos.
        /// </summary>
        internal static string JeraquiasObtener {
            get {
                return ResourceManager.GetString("JeraquiasObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeraquias/ObtenerPorCriterio.
        /// </summary>
        internal static string JeraquiasObtenerPorCriterio {
            get {
                return ResourceManager.GetString("JeraquiasObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MedidasCobro/CambiarEstatus.
        /// </summary>
        internal static string MedidaCobroCambiarEstatus {
            get {
                return ResourceManager.GetString("MedidaCobroCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MedidasCobro/Save.
        /// </summary>
        internal static string MedidaCobroGuardar {
            get {
                return ResourceManager.GetString("MedidaCobroGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MedidasCobro/ObtenerTodos.
        /// </summary>
        internal static string MedidaCobroObtener {
            get {
                return ResourceManager.GetString("MedidaCobroObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MedidasCobro/ObtenerPorCriterio.
        /// </summary>
        internal static string MedidaCobroObtenerPorCriterio {
            get {
                return ResourceManager.GetString("MedidaCobroObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meses/ObtenerTodos.
        /// </summary>
        internal static string MesObtener {
            get {
                return ResourceManager.GetString("MesObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulos/CambiarEstatus.
        /// </summary>
        internal static string ModulosActualizar {
            get {
                return ResourceManager.GetString("ModulosActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulos/Save.
        /// </summary>
        internal static string ModulosGuardar {
            get {
                return ResourceManager.GetString("ModulosGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulos/ObtenerTodos.
        /// </summary>
        internal static string ModulosObtener {
            get {
                return ResourceManager.GetString("ModulosObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulos/ObtenerListado.
        /// </summary>
        internal static string ModulosObtenerListado {
            get {
                return ResourceManager.GetString("ModulosObtenerListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulos/ObtenerPorCriterio.
        /// </summary>
        internal static string ModulosObtenerPorCriterio {
            get {
                return ResourceManager.GetString("ModulosObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipios/ObtenerTodos.
        /// </summary>
        internal static string MunicipiosObtener {
            get {
                return ResourceManager.GetString("MunicipiosObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuotas/ObtenerTodosConceptos.
        /// </summary>
        internal static string ObtenerCuotasConceptos {
            get {
                return ResourceManager.GetString("ObtenerCuotasConceptos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodos/CambiarEstatus.
        /// </summary>
        internal static string PeriodoCambiarEstatus {
            get {
                return ResourceManager.GetString("PeriodoCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodos/Save.
        /// </summary>
        internal static string PeriodoGuardar {
            get {
                return ResourceManager.GetString("PeriodoGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodos/ObtenerTodos.
        /// </summary>
        internal static string PeriodoObtener {
            get {
                return ResourceManager.GetString("PeriodoObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodos/ObtenerPorCriterio.
        /// </summary>
        internal static string PeriodoObtenerPorCriterio {
            get {
                return ResourceManager.GetString("PeriodoObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantilla/Guardar.
        /// </summary>
        internal static string PlantillaGuadar {
            get {
                return ResourceManager.GetString("PlantillaGuadar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantilla/Obtener.
        /// </summary>
        internal static string PlantillaObtener {
            get {
                return ResourceManager.GetString("PlantillaObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantilla/ObtenerPorCriterio.
        /// </summary>
        internal static string PlantillaObtenerPorCriterio {
            get {
                return ResourceManager.GetString("PlantillaObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referencias/CambiarEstatus.
        /// </summary>
        internal static string ReferenciaCambiarEstatus {
            get {
                return ResourceManager.GetString("ReferenciaCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referencias/Save.
        /// </summary>
        internal static string ReferenciaGuardar {
            get {
                return ResourceManager.GetString("ReferenciaGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referencias/ObtenerTodos.
        /// </summary>
        internal static string ReferenciaObtener {
            get {
                return ResourceManager.GetString("ReferenciaObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referencias/ObtenerPorCriterio.
        /// </summary>
        internal static string ReferenciaObtenerPorCriterio {
            get {
                return ResourceManager.GetString("ReferenciaObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referencias/ObtenerId.
        /// </summary>
        internal static string ReferenciaObtenerPorId {
            get {
                return ResourceManager.GetString("ReferenciaObtenerPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegimenFiscal/ObtenerTodos.
        /// </summary>
        internal static string RegimenFiscalObtener {
            get {
                return ResourceManager.GetString("RegimenFiscalObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegimenFiscal/ObtenerPorCriterio.
        /// </summary>
        internal static string RegimenFiscalObtenerPorCriterio {
            get {
                return ResourceManager.GetString("RegimenFiscalObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles/CambiarEstatus.
        /// </summary>
        internal static string RolesActualizar {
            get {
                return ResourceManager.GetString("RolesActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles/Save.
        /// </summary>
        internal static string RolesGuardar {
            get {
                return ResourceManager.GetString("RolesGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulos/CambiarEstatus.
        /// </summary>
        internal static string RolesModulosActualizar {
            get {
                return ResourceManager.GetString("RolesModulosActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulosControl/CambiarEstatus.
        /// </summary>
        internal static string RolesModulosControlActualizar {
            get {
                return ResourceManager.GetString("RolesModulosControlActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulosControl/Save.
        /// </summary>
        internal static string RolesModulosControlGuardar {
            get {
                return ResourceManager.GetString("RolesModulosControlGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulosControl/ObtenerTodos.
        /// </summary>
        internal static string RolesModulosControlObtener {
            get {
                return ResourceManager.GetString("RolesModulosControlObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulosControl/ObtenerListado.
        /// </summary>
        internal static string RolesModulosControlObtenerListado {
            get {
                return ResourceManager.GetString("RolesModulosControlObtenerListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulosControl/ObtenerPorCriterio.
        /// </summary>
        internal static string RolesModulosControlObtenerPorCriterio {
            get {
                return ResourceManager.GetString("RolesModulosControlObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulos/Save.
        /// </summary>
        internal static string RolesModulosGuardar {
            get {
                return ResourceManager.GetString("RolesModulosGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulos/ObtenerTodos.
        /// </summary>
        internal static string RolesModulosObtener {
            get {
                return ResourceManager.GetString("RolesModulosObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulos/ObtenerListado.
        /// </summary>
        internal static string RolesModulosObtenerListado {
            get {
                return ResourceManager.GetString("RolesModulosObtenerListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulos/ObtenerPorCriterio.
        /// </summary>
        internal static string RolesModulosObtenerPorCriterio {
            get {
                return ResourceManager.GetString("RolesModulosObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles/ObtenerTodos.
        /// </summary>
        internal static string RolesObtener {
            get {
                return ResourceManager.GetString("RolesObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles/ObtenerListado.
        /// </summary>
        internal static string RolesObtenerListado {
            get {
                return ResourceManager.GetString("RolesObtenerListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles/ObtenerPorCriterio.
        /// </summary>
        internal static string RolesObtenerPorCriterio {
            get {
                return ResourceManager.GetString("RolesObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesUsuarios/CambiarEstatus.
        /// </summary>
        internal static string RolesUsuariosActualizar {
            get {
                return ResourceManager.GetString("RolesUsuariosActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesUsuarios/Save.
        /// </summary>
        internal static string RolesUsuariosGuardar {
            get {
                return ResourceManager.GetString("RolesUsuariosGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesUsuarios/ObtenerTodos.
        /// </summary>
        internal static string RolesUsuariosObtener {
            get {
                return ResourceManager.GetString("RolesUsuariosObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesUsuarios/ObtenerListado.
        /// </summary>
        internal static string RolesUsuariosObtenerListado {
            get {
                return ResourceManager.GetString("RolesUsuariosObtenerListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesUsuarios/ObtenerPorCriterio.
        /// </summary>
        internal static string RolesUsuariosObtenerPorCriterio {
            get {
                return ResourceManager.GetString("RolesUsuariosObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector/ObtenerTodos.
        /// </summary>
        internal static string SectorObtener {
            get {
                return ResourceManager.GetString("SectorObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposContacto/ObtenerTodos.
        /// </summary>
        internal static string TipoContactoObtener {
            get {
                return ResourceManager.GetString("TipoContactoObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipoDocumento/CambiarEstatus.
        /// </summary>
        internal static string TipoDocumentoCambiarEstatus {
            get {
                return ResourceManager.GetString("TipoDocumentoCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipoDocumento/Save.
        /// </summary>
        internal static string TipoDocumentoGuardar {
            get {
                return ResourceManager.GetString("TipoDocumentoGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipoDocumento/ObtenerTodos.
        /// </summary>
        internal static string TipoDocumentoObtener {
            get {
                return ResourceManager.GetString("TipoDocumentoObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipoDocumento/ObtenerPorCriterio.
        /// </summary>
        internal static string TipoDocumentoObtenerPorCriterio {
            get {
                return ResourceManager.GetString("TipoDocumentoObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposControl/CambiarEstatus.
        /// </summary>
        internal static string TiposControlActualizar {
            get {
                return ResourceManager.GetString("TiposControlActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposControl/Save.
        /// </summary>
        internal static string TiposControlGuardar {
            get {
                return ResourceManager.GetString("TiposControlGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposControl/ObtenerTodos.
        /// </summary>
        internal static string TiposControlObtener {
            get {
                return ResourceManager.GetString("TiposControlObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposControl/ObtenerListado.
        /// </summary>
        internal static string TiposControlObtenerListado {
            get {
                return ResourceManager.GetString("TiposControlObtenerListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposControl/ObtenerPorCriterio.
        /// </summary>
        internal static string TiposControlObtenerPorCriterio {
            get {
                return ResourceManager.GetString("TiposControlObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposPago/ObtenerTodos.
        /// </summary>
        internal static string TiposPagoObtener {
            get {
                return ResourceManager.GetString("TiposPagoObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposPago/ObtenerPorCriterio.
        /// </summary>
        internal static string TiposPagoObtenerPorCriterio {
            get {
                return ResourceManager.GetString("TiposPagoObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposServicios/CambiarEstatus.
        /// </summary>
        internal static string TiposServicioCambiarEstatus {
            get {
                return ResourceManager.GetString("TiposServicioCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposServicios/Save.
        /// </summary>
        internal static string TiposServicioGuardar {
            get {
                return ResourceManager.GetString("TiposServicioGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposServicios/ObtenerTodos.
        /// </summary>
        internal static string TiposServicioObtener {
            get {
                return ResourceManager.GetString("TiposServicioObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposServicios/ObtenerPorCriterio.
        /// </summary>
        internal static string TiposServicioObtenerPorCriterio {
            get {
                return ResourceManager.GetString("TiposServicioObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposTelefono/Obtener.
        /// </summary>
        internal static string TipoTelefonoObtener {
            get {
                return ResourceManager.GetString("TipoTelefonoObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios/CambiarEstatus.
        /// </summary>
        internal static string UsuariosActualizar {
            get {
                return ResourceManager.GetString("UsuariosActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios/Save.
        /// </summary>
        internal static string UsuariosGuardar {
            get {
                return ResourceManager.GetString("UsuariosGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios/ObtenerTodos.
        /// </summary>
        internal static string UsuariosObtener {
            get {
                return ResourceManager.GetString("UsuariosObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios/ObtenerListado.
        /// </summary>
        internal static string UsuariosObtenerListado {
            get {
                return ResourceManager.GetString("UsuariosObtenerListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios/ObtenerPorCriterio.
        /// </summary>
        internal static string UsuariosObtenerPorCriterio {
            get {
                return ResourceManager.GetString("UsuariosObtenerPorCriterio", resourceCulture);
            }
        }
    }
}
