//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOB.SPF.ConecII.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MethodApiCatalog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MethodApiCatalog() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GOB.SPF.ConecII.Web.Resources.MethodApiCatalog", typeof(MethodApiCatalog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividades/ObtenerTodos.
        /// </summary>
        internal static string ActividadObtener {
            get {
                return ResourceManager.GetString("ActividadObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividades/ObtenerPorCriterio.
        /// </summary>
        internal static string ActividadObtenerPorCriterio {
            get {
                return ResourceManager.GetString("ActividadObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anios/ObtenerTodos.
        /// </summary>
        internal static string AnioObtener {
            get {
                return ResourceManager.GetString("AnioObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Areas/ObtenerTodos.
        /// </summary>
        internal static string AreaObtener {
            get {
                return ResourceManager.GetString("AreaObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Areas/ObtenerPorCriterio.
        /// </summary>
        internal static string AreaObtenerPorCriterio {
            get {
                return ResourceManager.GetString("AreaObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ClasificacionFactor/CambiarEstatus.
        /// </summary>
        internal static string ClasificacionFactorCambiarEstatus {
            get {
                return ResourceManager.GetString("ClasificacionFactorCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ClasificacionFactor/Save.
        /// </summary>
        internal static string ClasificacionFactorGuardar {
            get {
                return ResourceManager.GetString("ClasificacionFactorGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ClasificacionFactor/ObtenerTodos.
        /// </summary>
        internal static string ClasificacionFactorObtener {
            get {
                return ResourceManager.GetString("ClasificacionFactorObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ClasificacionFactor/ObtenerPorCriterio.
        /// </summary>
        internal static string ClasificacionFactorObtenerPorCriterio {
            get {
                return ResourceManager.GetString("ClasificacionFactorObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ConfigServ/InsertarConfiguraciones.
        /// </summary>
        internal static string ConfiguracionServicioInsertarConfiguraciones {
            get {
                return ResourceManager.GetString("ConfiguracionServicioInsertarConfiguraciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ConfigServ/ObtenerTodoPaginado.
        /// </summary>
        internal static string ConfiguracionServicioObtenerPaginado {
            get {
                return ResourceManager.GetString("ConfiguracionServicioObtenerPaginado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ConfigServ/ObtenerPorId.
        /// </summary>
        internal static string ConfiguracionServicioObtenerPorId {
            get {
                return ResourceManager.GetString("ConfiguracionServicioObtenerPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ConfigServ/ObtenerPorIdTipoServicioIdCentroCosto.
        /// </summary>
        internal static string ConfiguracionServicioObtenerPorIdTipoServicioIdCentroCosto {
            get {
                return ResourceManager.GetString("ConfiguracionServicioObtenerPorIdTipoServicioIdCentroCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controles/CambiarEstatus.
        /// </summary>
        internal static string ControlesActualizar {
            get {
                return ResourceManager.GetString("ControlesActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controles/Save.
        /// </summary>
        internal static string ControlesGuardar {
            get {
                return ResourceManager.GetString("ControlesGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controles/ObtenerTodos.
        /// </summary>
        internal static string ControlesObtener {
            get {
                return ResourceManager.GetString("ControlesObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controles/ObtenerListado.
        /// </summary>
        internal static string ControlesObtenerListado {
            get {
                return ResourceManager.GetString("ControlesObtenerListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controles/ObtenerPorCriterio.
        /// </summary>
        internal static string ControlesObtenerPorCriterio {
            get {
                return ResourceManager.GetString("ControlesObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuotas/CambiarEstatus.
        /// </summary>
        internal static string CuotaCambiarEstatus {
            get {
                return ResourceManager.GetString("CuotaCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuotas/Save.
        /// </summary>
        internal static string CuotaGuardar {
            get {
                return ResourceManager.GetString("CuotaGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuotas/ObtenerTodos.
        /// </summary>
        internal static string CuotaObtener {
            get {
                return ResourceManager.GetString("CuotaObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuotas/ObtenerPorCriterio.
        /// </summary>
        internal static string CuotaObtenerPorCriterio {
            get {
                return ResourceManager.GetString("CuotaObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dependencias/CambiarEstatus.
        /// </summary>
        internal static string DependenciaCambiarEstatus {
            get {
                return ResourceManager.GetString("DependenciaCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dependencias/Save.
        /// </summary>
        internal static string DependenciaGuardar {
            get {
                return ResourceManager.GetString("DependenciaGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dependencias/ObtenerTodos.
        /// </summary>
        internal static string DependenciaObtener {
            get {
                return ResourceManager.GetString("DependenciaObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dependencias/ObtenerPorCriterio.
        /// </summary>
        internal static string DependenciaObtenerPorCriterio {
            get {
                return ResourceManager.GetString("DependenciaObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divisiones/CambiarEstatus.
        /// </summary>
        internal static string DivisionesActualizar {
            get {
                return ResourceManager.GetString("DivisionesActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divisiones/Save.
        /// </summary>
        internal static string DivisionesGuardar {
            get {
                return ResourceManager.GetString("DivisionesGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divisiones/ObtenerTodos.
        /// </summary>
        internal static string DivisionesObtener {
            get {
                return ResourceManager.GetString("DivisionesObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divisiones/ObtenerListado.
        /// </summary>
        internal static string DivisionesObtenerListado {
            get {
                return ResourceManager.GetString("DivisionesObtenerListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divisiones/ObtenerPorCriterio.
        /// </summary>
        internal static string DivisionesObtenerPorCriterio {
            get {
                return ResourceManager.GetString("DivisionesObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estados/ObtenerTodos.
        /// </summary>
        internal static string EstadoObtener {
            get {
                return ResourceManager.GetString("EstadoObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factores/CambiarEstatus.
        /// </summary>
        internal static string FactorCambiarEstatus {
            get {
                return ResourceManager.GetString("FactorCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FactoresEntidadFederativa/CambiarEstatus.
        /// </summary>
        internal static string FactorEntidadFederativaCambiarEstatus {
            get {
                return ResourceManager.GetString("FactorEntidadFederativaCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FactoresEntidadFederativa/Save.
        ///   Looks up a localized string similar to FactorEntidadFederativa/Obtener/.
        /// </summary>
        internal static string FactorEntidadFederativaDTOObtener {
            get {
                return ResourceManager.GetString("FactorEntidadFederativaDTOObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresEntidadFederativa/ObtenerEstados.
        /// </summary>
        internal static string FactorEntidadFederativaDTOObtenerEstados {
            get {
                return ResourceManager.GetString("FactorEntidadFederativaDTOObtenerEstados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factores/ObtenerFactorPorClasificacion.
        /// </summary>
        internal static string FactorEntidadFederativaDTOObtenerFactor {
            get {
                return ResourceManager.GetString("FactorEntidadFederativaDTOObtenerFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresEntidadFederativa/Save.
        /// </summary>
        internal static string FactorEntidadFederativaGuardar {
            get {
                return ResourceManager.GetString("FactorEntidadFederativaGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FactoresEntidadFederativa/ObtenerTodos.
        /// </summary>
        internal static string FactorEntidadFederativaObtener {
            get {
                return ResourceManager.GetString("FactorEntidadFederativaObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FactoresEntidadFederativa/ObtenerPorCriterio.
        /// </summary>
        internal static string FactorEntidadFederativaObtenerPorCriterio {
            get {
                return ResourceManager.GetString("FactorEntidadFederativaObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FactoresMunicipio/Obtener.
        /// </summary>
        internal static string FactoresMunicipioObtener {
            get {
                return ResourceManager.GetString("FactoresMunicipioObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factores/Save.
        /// </summary>
        internal static string FactorGuardar {
            get {
                return ResourceManager.GetString("FactorGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FactoresLeyIngreso/CambiarEstatus.
        /// </summary>
        internal static string FactorLeyIngresoCambiarEstatus {
            get {
                return ResourceManager.GetString("FactorLeyIngresoCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FactoresLeyIngreso/Save.
        /// </summary>
        internal static string FactorLeyIngresoGuardar {
            get {
                return ResourceManager.GetString("FactorLeyIngresoGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FactoresLeyIngreso/ObtenerTodos.
        /// </summary>
        internal static string FactorLeyIngresoObtener {
            get {
                return ResourceManager.GetString("FactorLeyIngresoObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FactoresLeyIngreso/ObtenerPorCriterio.
        /// </summary>
        internal static string FactorLeyIngresoObtenerPorCriterio {
            get {
                return ResourceManager.GetString("FactorLeyIngresoObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FactoresMunicipio/Save.
        /// </summary>
        internal static string FactorMunicipioGuardar {
            get {
                return ResourceManager.GetString("FactorMunicipioGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factores/ObtenerTodos.
        /// </summary>
        internal static string FactorObtener {
            get {
                return ResourceManager.GetString("FactorObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factores/FactorObtenerPorClasificacion.
        /// </summary>
        internal static string FactorObtenerPorClasificacion {
            get {
                return ResourceManager.GetString("FactorObtenerPorClasificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factores/ObtenerPorCriterio.
        /// </summary>
        internal static string FactorObtenerPorCriterio {
            get {
                return ResourceManager.GetString("FactorObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fases/ObtenerTodos.
        /// </summary>
        internal static string FasesObtener {
            get {
                return ResourceManager.GetString("FasesObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fases/ObtenerPorCriterio.
        /// </summary>
        internal static string FasesObtenerPorCriterio {
            get {
                return ResourceManager.GetString("FasesObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fracciones/CambiarEstatus.
        /// </summary>
        internal static string FraccionesCambiarEstatus {
            get {
                return ResourceManager.GetString("FraccionesCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fracciones/Save.
        /// </summary>
        internal static string FraccionesGuardar {
            get {
                return ResourceManager.GetString("FraccionesGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fracciones/ObtenerTodos.
        /// </summary>
        internal static string FraccionesObtener {
            get {
                return ResourceManager.GetString("FraccionesObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fracciones/ObtenerPorCriterio.
        /// </summary>
        internal static string FraccionesObtenerPorCriterio {
            get {
                return ResourceManager.GetString("FraccionesObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fracciones/ValidarRegistro.
        /// </summary>
        internal static string FraccionValidar {
            get {
                return ResourceManager.GetString("FraccionValidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GastosInherentes/CambiarEstatus.
        /// </summary>
        internal static string GastosInherenteCambiarEstatus {
            get {
                return ResourceManager.GetString("GastosInherenteCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GastosInherentes/Save.
        /// </summary>
        internal static string GastosInherenteGuardar {
            get {
                return ResourceManager.GetString("GastosInherenteGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GastosInherentes/ObtenerTodos.
        /// </summary>
        internal static string GastosInherenteObtener {
            get {
                return ResourceManager.GetString("GastosInherenteObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GastosInherentes/ObtenerPorCriterio.
        /// </summary>
        internal static string GastosInherenteObtenerPorCriterio {
            get {
                return ResourceManager.GetString("GastosInherenteObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo/CambiarEstatus.
        /// </summary>
        internal static string GrupoActualizar {
            get {
                return ResourceManager.GetString("GrupoActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo/Save.
        /// </summary>
        internal static string GrupoGuardar {
            get {
                return ResourceManager.GetString("GrupoGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo/ObtenerTodos.
        /// </summary>
        internal static string GrupoObtener {
            get {
                return ResourceManager.GetString("GrupoObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo/ObtenerPorCriterio.
        /// </summary>
        internal static string GrupoObtenerPorCriterio {
            get {
                return ResourceManager.GetString("GrupoObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupos/ObtenerIdDivision/.
        /// </summary>
        internal static string GrupoObtenerPorIdDivision {
            get {
                return ResourceManager.GetString("GrupoObtenerPorIdDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GrupoTarifarios/CambiarEstatus.
        /// </summary>
        internal static string GrupoTarifariosCambiarEstatus {
            get {
                return ResourceManager.GetString("GrupoTarifariosCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GrupoTarifarios/Save.
        /// </summary>
        internal static string GrupoTarifariosGuardar {
            get {
                return ResourceManager.GetString("GrupoTarifariosGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GruposTarifario/ObtenerTodos.
        /// </summary>
        internal static string GrupoTarifariosObtener {
            get {
                return ResourceManager.GetString("GrupoTarifariosObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GrupoTarifarios/ObtenerPorCriterio.
        /// </summary>
        internal static string GrupoTarifariosObtenerPorCriterio {
            get {
                return ResourceManager.GetString("GrupoTarifariosObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integrantes/ObtenerTodos.
        /// </summary>
        internal static string IntegrantesObtener {
            get {
                return ResourceManager.GetString("IntegrantesObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integrantes/ObtenerPorCriterio.
        /// </summary>
        internal static string IntegrantesObtenerPorCriterio {
            get {
                return ResourceManager.GetString("IntegrantesObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jeraquias/CambiarEstatus.
        /// </summary>
        internal static string JeraquiasCambiarEstatus {
            get {
                return ResourceManager.GetString("JeraquiasCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jeraquias/Save.
        /// </summary>
        internal static string JeraquiasGuardar {
            get {
                return ResourceManager.GetString("JeraquiasGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jerarquias/ObtenerTodos.
        /// </summary>
        internal static string JeraquiasObtener {
            get {
                return ResourceManager.GetString("JeraquiasObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jeraquias/ObtenerPorCriterio.
        /// </summary>
        internal static string JeraquiasObtenerPorCriterio {
            get {
                return ResourceManager.GetString("JeraquiasObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MedidasCobro/CambiarEstatus.
        /// </summary>
        internal static string MedidaCobroCambiarEstatus {
            get {
                return ResourceManager.GetString("MedidaCobroCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MedidasCobro/Save.
        /// </summary>
        internal static string MedidaCobroGuardar {
            get {
                return ResourceManager.GetString("MedidaCobroGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MedidasCobro/ObtenerTodos.
        /// </summary>
        internal static string MedidaCobroObtener {
            get {
                return ResourceManager.GetString("MedidaCobroObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MedidasCobro/ObtenerPorCriterio.
        /// </summary>
        internal static string MedidaCobroObtenerPorCriterio {
            get {
                return ResourceManager.GetString("MedidaCobroObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meses/ObtenerTodos.
        /// </summary>
        internal static string MesObtener {
            get {
                return ResourceManager.GetString("MesObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulos/CambiarEstatus.
        /// </summary>
        internal static string ModulosActualizar {
            get {
                return ResourceManager.GetString("ModulosActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulos/Save.
        /// </summary>
        internal static string ModulosGuardar {
            get {
                return ResourceManager.GetString("ModulosGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulos/ObtenerTodos.
        /// </summary>
        internal static string ModulosObtener {
            get {
                return ResourceManager.GetString("ModulosObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulos/ObtenerListado.
        /// </summary>
        internal static string ModulosObtenerListado {
            get {
                return ResourceManager.GetString("ModulosObtenerListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulos/ObtenerPorCriterio.
        /// </summary>
        internal static string ModulosObtenerPorCriterio {
            get {
                return ResourceManager.GetString("ModulosObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipios/ObtenerTodos.
        /// </summary>
        internal static string MunicipiosObtener {
            get {
                return ResourceManager.GetString("MunicipiosObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodos/CambiarEstatus.
        /// </summary>
        internal static string PeriodoCambiarEstatus {
            get {
                return ResourceManager.GetString("PeriodoCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodos/Save.
        /// </summary>
        internal static string PeriodoGuardar {
            get {
                return ResourceManager.GetString("PeriodoGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodos/ObtenerTodos.
        /// </summary>
        internal static string PeriodoObtener {
            get {
                return ResourceManager.GetString("PeriodoObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodos/ObtenerPorCriterio.
        /// </summary>
        internal static string PeriodoObtenerPorCriterio {
            get {
                return ResourceManager.GetString("PeriodoObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plantilla/Guardar.
        /// </summary>
        internal static string PlantillaGuadar {
            get {
                return ResourceManager.GetString("PlantillaGuadar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plantilla/Obtener.
        /// </summary>
        internal static string PlantillaObtener {
            get {
                return ResourceManager.GetString("PlantillaObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plantilla/ObtenerPorCriterio.
        /// </summary>
        internal static string PlantillaObtenerPorCriterio {
            get {
                return ResourceManager.GetString("PlantillaObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencias/CambiarEstatus.
        /// </summary>
        internal static string ReferenciaCambiarEstatus {
            get {
                return ResourceManager.GetString("ReferenciaCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencias/Save.
        /// </summary>
        internal static string ReferenciaGuardar {
            get {
                return ResourceManager.GetString("ReferenciaGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencias/ObtenerTodos.
        /// </summary>
        internal static string ReferenciaObtener {
            get {
                return ResourceManager.GetString("ReferenciaObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencias/ObtenerPorCriterio.
        /// </summary>
        internal static string ReferenciaObtenerPorCriterio {
            get {
                return ResourceManager.GetString("ReferenciaObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RegimenFiscal/ObtenerTodos.
        /// </summary>
        internal static string RegimenFiscalObtener {
            get {
                return ResourceManager.GetString("RegimenFiscalObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RegimenFiscal/ObtenerPorCriterio.
        /// </summary>
        internal static string RegimenFiscalObtenerPorCriterio {
            get {
                return ResourceManager.GetString("RegimenFiscalObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles/CambiarEstatus.
        /// </summary>
        internal static string RolesActualizar {
            get {
                return ResourceManager.GetString("RolesActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles/Save.
        /// </summary>
        internal static string RolesGuardar {
            get {
                return ResourceManager.GetString("RolesGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulos/CambiarEstatus.
        /// </summary>
        internal static string RolesModulosActualizar {
            get {
                return ResourceManager.GetString("RolesModulosActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulosControl/CambiarEstatus.
        /// </summary>
        internal static string RolesModulosControlActualizar {
            get {
                return ResourceManager.GetString("RolesModulosControlActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulosControl/Save.
        /// </summary>
        internal static string RolesModulosControlGuardar {
            get {
                return ResourceManager.GetString("RolesModulosControlGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulosControl/ObtenerTodos.
        /// </summary>
        internal static string RolesModulosControlObtener {
            get {
                return ResourceManager.GetString("RolesModulosControlObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulosControl/ObtenerListado.
        /// </summary>
        internal static string RolesModulosControlObtenerListado {
            get {
                return ResourceManager.GetString("RolesModulosControlObtenerListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulosControl/ObtenerPorCriterio.
        /// </summary>
        internal static string RolesModulosControlObtenerPorCriterio {
            get {
                return ResourceManager.GetString("RolesModulosControlObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulos/Save.
        /// </summary>
        internal static string RolesModulosGuardar {
            get {
                return ResourceManager.GetString("RolesModulosGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulos/ObtenerTodos.
        /// </summary>
        internal static string RolesModulosObtener {
            get {
                return ResourceManager.GetString("RolesModulosObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulos/ObtenerListado.
        /// </summary>
        internal static string RolesModulosObtenerListado {
            get {
                return ResourceManager.GetString("RolesModulosObtenerListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesModulos/ObtenerPorCriterio.
        /// </summary>
        internal static string RolesModulosObtenerPorCriterio {
            get {
                return ResourceManager.GetString("RolesModulosObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles/ObtenerTodos.
        /// </summary>
        internal static string RolesObtener {
            get {
                return ResourceManager.GetString("RolesObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles/ObtenerListado.
        /// </summary>
        internal static string RolesObtenerListado {
            get {
                return ResourceManager.GetString("RolesObtenerListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles/ObtenerPorCriterio.
        /// </summary>
        internal static string RolesObtenerPorCriterio {
            get {
                return ResourceManager.GetString("RolesObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesUsuarios/CambiarEstatus.
        /// </summary>
        internal static string RolesUsuariosActualizar {
            get {
                return ResourceManager.GetString("RolesUsuariosActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesUsuarios/Save.
        /// </summary>
        internal static string RolesUsuariosGuardar {
            get {
                return ResourceManager.GetString("RolesUsuariosGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesUsuarios/ObtenerTodos.
        /// </summary>
        internal static string RolesUsuariosObtener {
            get {
                return ResourceManager.GetString("RolesUsuariosObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesUsuarios/ObtenerListado.
        /// </summary>
        internal static string RolesUsuariosObtenerListado {
            get {
                return ResourceManager.GetString("RolesUsuariosObtenerListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesUsuarios/ObtenerPorCriterio.
        /// </summary>
        internal static string RolesUsuariosObtenerPorCriterio {
            get {
                return ResourceManager.GetString("RolesUsuariosObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipoDocumento/CambiarEstatus.
        /// </summary>
        internal static string SectorObtener {
            get {
                return ResourceManager.GetString("SectorObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TipoDocumento/CambiarEstatus.
        /// </summary>
        internal static string TipoDocumentoCambiarEstatus {
            get {
                return ResourceManager.GetString("TipoDocumentoCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TipoDocumento/Save.
        /// </summary>
        internal static string TipoDocumentoGuardar {
            get {
                return ResourceManager.GetString("TipoDocumentoGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TipoDocumento/ObtenerTodos.
        /// </summary>
        internal static string TipoDocumentoObtener {
            get {
                return ResourceManager.GetString("TipoDocumentoObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TipoDocumento/ObtenerPorCriterio.
        /// </summary>
        internal static string TipoDocumentoObtenerPorCriterio {
            get {
                return ResourceManager.GetString("TipoDocumentoObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposControl/CambiarEstatus.
        /// </summary>
        internal static string TiposControlActualizar {
            get {
                return ResourceManager.GetString("TiposControlActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposControl/Save.
        /// </summary>
        internal static string TiposControlGuardar {
            get {
                return ResourceManager.GetString("TiposControlGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposControl/ObtenerTodos.
        /// </summary>
        internal static string TiposControlObtener {
            get {
                return ResourceManager.GetString("TiposControlObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposControl/ObtenerListado.
        /// </summary>
        internal static string TiposControlObtenerListado {
            get {
                return ResourceManager.GetString("TiposControlObtenerListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposControl/ObtenerPorCriterio.
        /// </summary>
        internal static string TiposControlObtenerPorCriterio {
            get {
                return ResourceManager.GetString("TiposControlObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposPago/ObtenerTodos.
        /// </summary>
        internal static string TiposPagoObtener {
            get {
                return ResourceManager.GetString("TiposPagoObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TiposPago/ObtenerPorCriterio.
        /// </summary>
        internal static string TiposPagoObtenerPorCriterio {
            get {
                return ResourceManager.GetString("TiposPagoObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TiposServicios/CambiarEstatus.
        /// </summary>
        internal static string TiposServicioCambiarEstatus {
            get {
                return ResourceManager.GetString("TiposServicioCambiarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TiposServicios/Save.
        /// </summary>
        internal static string TiposServicioGuardar {
            get {
                return ResourceManager.GetString("TiposServicioGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TiposServicios/ObtenerTodos.
        /// </summary>
        internal static string TiposServicioObtener {
            get {
                return ResourceManager.GetString("TiposServicioObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TiposServicios/ObtenerPorCriterio.
        /// </summary>
        internal static string TiposServicioObtenerPorCriterio {
            get {
                return ResourceManager.GetString("TiposServicioObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios/CambiarEstatus.
        /// </summary>
        internal static string UsuariosActualizar {
            get {
                return ResourceManager.GetString("UsuariosActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios/Save.
        /// </summary>
        internal static string UsuariosGuardar {
            get {
                return ResourceManager.GetString("UsuariosGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios/ObtenerTodos.
        /// </summary>
        internal static string UsuariosObtener {
            get {
                return ResourceManager.GetString("UsuariosObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios/ObtenerListado.
        /// </summary>
        internal static string UsuariosObtenerListado {
            get {
                return ResourceManager.GetString("UsuariosObtenerListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios/ObtenerPorCriterio.
        /// </summary>
        internal static string UsuariosObtenerPorCriterio {
            get {
                return ResourceManager.GetString("UsuariosObtenerPorCriterio", resourceCulture);
            }
        }
    }
}
