//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36366
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsBroxel.PaymentService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcceptPaymentDTO", Namespace="http://schemas.datacontract.org/2004/07/PS.IssuerCommercial.ClientWS.Contract.Dat" +
        "atypes")]
    [System.SerializableAttribute()]
    public partial class AcceptPaymentDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CurrencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalPaymentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneralAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsConfirmationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PaymentChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PaymentMethodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalInformation {
            get {
                return this.AdditionalInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalInformationField, value) != true)) {
                    this.AdditionalInformationField = value;
                    this.RaisePropertyChanged("AdditionalInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CurrencyCode {
            get {
                return this.CurrencyCodeField;
            }
            set {
                if ((this.CurrencyCodeField.Equals(value) != true)) {
                    this.CurrencyCodeField = value;
                    this.RaisePropertyChanged("CurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalPaymentCode {
            get {
                return this.ExternalPaymentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalPaymentCodeField, value) != true)) {
                    this.ExternalPaymentCodeField = value;
                    this.RaisePropertyChanged("ExternalPaymentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneralAccountNumber {
            get {
                return this.GeneralAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneralAccountNumberField, value) != true)) {
                    this.GeneralAccountNumberField = value;
                    this.RaisePropertyChanged("GeneralAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsConfirmation {
            get {
                return this.IsConfirmationField;
            }
            set {
                if ((this.IsConfirmationField.Equals(value) != true)) {
                    this.IsConfirmationField = value;
                    this.RaisePropertyChanged("IsConfirmation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short PaymentChannel {
            get {
                return this.PaymentChannelField;
            }
            set {
                if ((this.PaymentChannelField.Equals(value) != true)) {
                    this.PaymentChannelField = value;
                    this.RaisePropertyChanged("PaymentChannel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentDate {
            get {
                return this.PaymentDateField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentDateField, value) != true)) {
                    this.PaymentDateField = value;
                    this.RaisePropertyChanged("PaymentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short PaymentMethod {
            get {
                return this.PaymentMethodField;
            }
            set {
                if ((this.PaymentMethodField.Equals(value) != true)) {
                    this.PaymentMethodField = value;
                    this.RaisePropertyChanged("PaymentMethod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/PS.CommonCredit.ClientWS.Contract.Datatyp" +
        "es")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsBroxel.PaymentService.PaymentResponseDTO))]
    public partial class ResponseDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wsBroxel.PaymentService.ErrorDTO[] ErrorsField;
        
        private wsBroxel.PaymentService.ReturnExecution ReturnExecutionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsBroxel.PaymentService.ErrorDTO[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public wsBroxel.PaymentService.ReturnExecution ReturnExecution {
            get {
                return this.ReturnExecutionField;
            }
            set {
                if ((this.ReturnExecutionField.Equals(value) != true)) {
                    this.ReturnExecutionField = value;
                    this.RaisePropertyChanged("ReturnExecution");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/PS.IssuerCommercial.ClientWS.Contract.Dat" +
        "atypes")]
    [System.SerializableAttribute()]
    public partial class PaymentResponseDTO : wsBroxel.PaymentService.ResponseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wsBroxel.PaymentService.PaymentInfoDTO paymentInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsBroxel.PaymentService.PaymentInfoDTO paymentInfo {
            get {
                return this.paymentInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.paymentInfoField, value) != true)) {
                    this.paymentInfoField = value;
                    this.RaisePropertyChanged("paymentInfo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorDTO", Namespace="http://schemas.datacontract.org/2004/07/PS.CommonCredit.ClientWS.Contract.Datatyp" +
        "es")]
    [System.SerializableAttribute()]
    public partial class ErrorDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorCodeField;
        
        private string ErrorTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ErrorText {
            get {
                return this.ErrorTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorTextField, value) != true)) {
                    this.ErrorTextField = value;
                    this.RaisePropertyChanged("ErrorText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnExecution", Namespace="http://schemas.datacontract.org/2004/07/PS.CommonCredit.ClientWS.Contract.Enumera" +
        "tions")]
    public enum ReturnExecution : short {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUCCESS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WITH_ERROR = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WITH_WARNING = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentInfoDTO", Namespace="http://schemas.datacontract.org/2004/07/PS.IssuerCommercial.ClientWS.Contract.Dat" +
        "atypes")]
    [System.SerializableAttribute()]
    public partial class PaymentInfoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentCode {
            get {
                return this.PaymentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentCodeField, value) != true)) {
                    this.PaymentCodeField = value;
                    this.RaisePropertyChanged("PaymentCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UndoPaymentDTO", Namespace="http://schemas.datacontract.org/2004/07/PS.IssuerCommercial.ClientWS.Contract.Dat" +
        "atypes")]
    [System.SerializableAttribute()]
    public partial class UndoPaymentDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> CurrencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> GeneralAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UndoReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> CurrencyCode {
            get {
                return this.CurrencyCodeField;
            }
            set {
                if ((this.CurrencyCodeField.Equals(value) != true)) {
                    this.CurrencyCodeField = value;
                    this.RaisePropertyChanged("CurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> GeneralAccountNumber {
            get {
                return this.GeneralAccountNumberField;
            }
            set {
                if ((this.GeneralAccountNumberField.Equals(value) != true)) {
                    this.GeneralAccountNumberField = value;
                    this.RaisePropertyChanged("GeneralAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentCode {
            get {
                return this.PaymentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentCodeField, value) != true)) {
                    this.PaymentCodeField = value;
                    this.RaisePropertyChanged("PaymentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentDate {
            get {
                return this.PaymentDateField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentDateField, value) != true)) {
                    this.PaymentDateField = value;
                    this.RaisePropertyChanged("PaymentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UndoReason {
            get {
                return this.UndoReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.UndoReasonField, value) != true)) {
                    this.UndoReasonField = value;
                    this.RaisePropertyChanged("UndoReason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaymentService.IPaymentService")]
    public interface IPaymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/AcceptPayment", ReplyAction="http://tempuri.org/IPaymentService/AcceptPaymentResponse")]
        wsBroxel.PaymentService.PaymentResponseDTO AcceptPayment(string issuerCode, wsBroxel.PaymentService.AcceptPaymentDTO payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/UndoPayment", ReplyAction="http://tempuri.org/IPaymentService/UndoPaymentResponse")]
        wsBroxel.PaymentService.PaymentResponseDTO UndoPayment(wsBroxel.PaymentService.UndoPaymentDTO payment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentServiceChannel : wsBroxel.PaymentService.IPaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentServiceClient : System.ServiceModel.ClientBase<wsBroxel.PaymentService.IPaymentService>, wsBroxel.PaymentService.IPaymentService {
        
        public PaymentServiceClient() {
        }
        
        public PaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public wsBroxel.PaymentService.PaymentResponseDTO AcceptPayment(string issuerCode, wsBroxel.PaymentService.AcceptPaymentDTO payment) {
            return base.Channel.AcceptPayment(issuerCode, payment);
        }
        
        public wsBroxel.PaymentService.PaymentResponseDTO UndoPayment(wsBroxel.PaymentService.UndoPaymentDTO payment) {
            return base.Channel.UndoPayment(payment);
        }
    }
}
