//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComCredencial
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgrupacionClientes
    {
        public long id { get; set; }
        public bool GrupoFiscal { get; set; }
        public string ClaveAgrupacion { get; set; }
        public string NombreCorto { get; set; }
        public string razonSocial { get; set; }
        public Nullable<System.DateTime> fechaConstitucion { get; set; }
        public string rfc { get; set; }
        public string clavePais { get; set; }
        public Nullable<int> actividadEconomica { get; set; }
        public string nombreRepLegal { get; set; }
        public string aPaternoRegLegal { get; set; }
        public string aMaternoRepLegal { get; set; }
        public Nullable<System.DateTime> fechaNacimientoRepLegal { get; set; }
        public string rfcRepLegal { get; set; }
        public string curpRepLegal { get; set; }
        public string tipoIdRepLegal { get; set; }
        public string tipoIdOtroRepLegal { get; set; }
        public string autoridadEmiteRepLegal { get; set; }
        public string numIdentificacionRepLegal { get; set; }
        public string colonia { get; set; }
        public string calle { get; set; }
        public string numExt { get; set; }
        public string numInt { get; set; }
        public string codigoPostal { get; set; }
        public string paisTel { get; set; }
        public string tel { get; set; }
        public string CLABEDestino { get; set; }
        public string CorreoContacto { get; set; }
        public string Localidad { get; set; }
        public string Referencia { get; set; }
        public string MunicipioDelegacion { get; set; }
        public string Estado { get; set; }
        public bool ReportaPLD { get; set; }
        public bool EmiteFactura { get; set; }
    }
}
