//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComCredencial
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargosDisposicionesEfectivo
    {
        public long Id { get; set; }
        public int IdDisposicion { get; set; }
        public string NumCuenta { get; set; }
        public string NumTarjeta { get; set; }
        public Nullable<int> IdMovimiento { get; set; }
        public Nullable<double> Monto { get; set; }
        public Nullable<int> Autorizado { get; set; }
        public string NumAutorizacion { get; set; }
        public Nullable<System.DateTime> FechaHoraCreacion { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> IdReverso { get; set; }
        public Nullable<int> AutorizadoReverso { get; set; }
        public string NumAutorizacionReverso { get; set; }
        public Nullable<System.DateTime> FechaHoraReverso { get; set; }
    }
}
