//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComCredencial
{
    using System;
    using System.Collections.Generic;
    
    public partial class fechas_corte_x_grupos
    {
        public int id { get; set; }
        public string year { get; set; }
        public string mes { get; set; }
        public string dia { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> fecha_vto { get; set; }
        public string grupo { get; set; }
        public string semestre { get; set; }
        public Nullable<System.DateTime> fecha_recep_cobranzas { get; set; }
        public Nullable<System.DateTime> ult_dia_tablas_variables { get; set; }
        public Nullable<System.DateTime> liquidacion { get; set; }
    }
}
