//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOB.SPF.ConecII.AccessData.Schemas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Contraprestacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Contraprestacion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GOB.SPF.ConecII.AccessData.Schemas.Contraprestacion", typeof(Contraprestacion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraprestacion.sp_CetesActualizar.
        /// </summary>
        internal static string Contraprestacion_CetesActualizar {
            get {
                return ResourceManager.GetString("Contraprestacion.CetesActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraprestacion.sp_CetesInsertar.
        /// </summary>
        internal static string Contraprestacion_CetesInsertar {
            get {
                return ResourceManager.GetString("Contraprestacion.CetesInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraprestacion.sp_CetesObtenerPorCriterio.
        /// </summary>
        internal static string Contraprestacion_ObtenerPorCriterio {
            get {
                return ResourceManager.GetString("Contraprestacion.ObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraprestacion.sp_CetesObtenerPorFecha.
        /// </summary>
        internal static string Contraprestacion_ObtenerPorFecha {
            get {
                return ResourceManager.GetString("Contraprestacion.ObtenerPorFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraprestacion.sp_TesofeActualizar.
        /// </summary>
        internal static string Contraprestacion_TesofeActualizar {
            get {
                return ResourceManager.GetString("Contraprestacion.TesofeActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraprestacion.sp_TesofeInsertar.
        /// </summary>
        internal static string Contraprestacion_TesofeInsertar {
            get {
                return ResourceManager.GetString("Contraprestacion.TesofeInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraprestacion.sp_TesofeObtenerPorCriterio.
        /// </summary>
        internal static string Contraprestacion_TesofeObtenerPorCriterio {
            get {
                return ResourceManager.GetString("Contraprestacion.TesofeObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraprestacion.sp_TesofeObtenerPorId.
        /// </summary>
        internal static string Contraprestacion_TesofeObtenerPorId {
            get {
                return ResourceManager.GetString("Contraprestacion.TesofeObtenerPorId", resourceCulture);
            }
        }
    }
}
