//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsServices01800
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecalificacionResponse
    {
        public PrecalificacionResponse()
        {
            this.PrecalificacionOcur = new HashSet<PrecalificacionOcur>();
        }
    
        public long idPrecalificacion { get; set; }
        public string wsIdMensaje { get; set; }
        public string wsMensaje { get; set; }
        public string wsNumRegistroPatronal { get; set; }
        public string wsRFC { get; set; }
        public string wsNombreTitular { get; set; }
        public string wsCurp { get; set; }
        public Nullable<decimal> wsPuntMin { get; set; }
        public Nullable<decimal> wsPuntTotal { get; set; }
        public Nullable<int> wsNumPlazos { get; set; }
        public Nullable<decimal> wsGastosApertura { get; set; }
        public Nullable<decimal> wsTasaInteres { get; set; }
        public string WSNombreEmpresa { get; set; }
    
        public virtual ICollection<PrecalificacionOcur> PrecalificacionOcur { get; set; }
        public virtual PrecalificacionRequest PrecalificacionRequest { get; set; }
    }
}
