//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsServices01800
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecalificacionOcur
    {
        public long idPrecalificacion { get; set; }
        public int plazo { get; set; }
        public Nullable<decimal> monto_credito { get; set; }
        public Nullable<decimal> pago_mensual { get; set; }
        public Nullable<decimal> contarias { get; set; }
        public Nullable<decimal> mano_obra { get; set; }
    
        public virtual PrecalificacionResponse PrecalificacionResponse { get; set; }
    }
}
