//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroxelWSCore.wsSPEI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="https://www.broxel.com")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transferencia", Namespace="https://www.broxel.com")]
    [System.SerializableAttribute()]
    public partial class Transferencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClabeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDisposicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreBeneficiarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumCuentaBroxelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clabe {
            get {
                return this.ClabeField;
            }
            set {
                if ((object.ReferenceEquals(this.ClabeField, value) != true)) {
                    this.ClabeField = value;
                    this.RaisePropertyChanged("Clabe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDisposicion {
            get {
                return this.IdDisposicionField;
            }
            set {
                if ((this.IdDisposicionField.Equals(value) != true)) {
                    this.IdDisposicionField = value;
                    this.RaisePropertyChanged("IdDisposicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreBeneficiario {
            get {
                return this.NombreBeneficiarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreBeneficiarioField, value) != true)) {
                    this.NombreBeneficiarioField = value;
                    this.RaisePropertyChanged("NombreBeneficiario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumCuentaBroxel {
            get {
                return this.NumCuentaBroxelField;
            }
            set {
                if ((object.ReferenceEquals(this.NumCuentaBroxelField, value) != true)) {
                    this.NumCuentaBroxelField = value;
                    this.RaisePropertyChanged("NumCuentaBroxel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaTransferencia", Namespace="https://www.broxel.com")]
    [System.SerializableAttribute()]
    public partial class RespuestaTransferencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveRastreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuentaSTPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EnvioPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTransferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReferenciaPagoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveRastreo {
            get {
                return this.ClaveRastreoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveRastreoField, value) != true)) {
                    this.ClaveRastreoField = value;
                    this.RaisePropertyChanged("ClaveRastreo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaSTP {
            get {
                return this.CuentaSTPField;
            }
            set {
                if ((object.ReferenceEquals(this.CuentaSTPField, value) != true)) {
                    this.CuentaSTPField = value;
                    this.RaisePropertyChanged("CuentaSTP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EnvioPago {
            get {
                return this.EnvioPagoField;
            }
            set {
                if ((this.EnvioPagoField.Equals(value) != true)) {
                    this.EnvioPagoField = value;
                    this.RaisePropertyChanged("EnvioPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPago {
            get {
                return this.FechaPagoField;
            }
            set {
                if ((this.FechaPagoField.Equals(value) != true)) {
                    this.FechaPagoField = value;
                    this.RaisePropertyChanged("FechaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTransferencia {
            get {
                return this.IdTransferenciaField;
            }
            set {
                if ((this.IdTransferenciaField.Equals(value) != true)) {
                    this.IdTransferenciaField = value;
                    this.RaisePropertyChanged("IdTransferencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReferenciaPago {
            get {
                return this.ReferenciaPagoField;
            }
            set {
                if ((this.ReferenciaPagoField.Equals(value) != true)) {
                    this.ReferenciaPagoField = value;
                    this.RaisePropertyChanged("ReferenciaPago");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.broxel.com", ConfigurationName="wsSPEI.IwsSPEI")]
    public interface IwsSPEI {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.broxel.com/IwsSPEI/registraOrden", ReplyAction="https://www.broxel.com/IwsSPEI/registraOrdenResponse")]
        BroxelWSCore.wsSPEI.Respuesta registraOrden(int IdDetalleDiario);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.broxel.com/IwsSPEI/registraOrden", ReplyAction="https://www.broxel.com/IwsSPEI/registraOrdenResponse")]
        System.Threading.Tasks.Task<BroxelWSCore.wsSPEI.Respuesta> registraOrdenAsync(int IdDetalleDiario);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.broxel.com/IwsSPEI/registraTranferencia", ReplyAction="https://www.broxel.com/IwsSPEI/registraTranferenciaResponse")]
        BroxelWSCore.wsSPEI.RespuestaTransferencia registraTranferencia(BroxelWSCore.wsSPEI.Transferencia transferencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.broxel.com/IwsSPEI/registraTranferencia", ReplyAction="https://www.broxel.com/IwsSPEI/registraTranferenciaResponse")]
        System.Threading.Tasks.Task<BroxelWSCore.wsSPEI.RespuestaTransferencia> registraTranferenciaAsync(BroxelWSCore.wsSPEI.Transferencia transferencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.broxel.com/IwsSPEI/PagosRecibidosParaTerceros", ReplyAction="https://www.broxel.com/IwsSPEI/PagosRecibidosParaTercerosResponse")]
        BroxelWSCore.wsSPEI.Respuesta PagosRecibidosParaTerceros(string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.broxel.com/IwsSPEI/PagosRecibidosParaTerceros", ReplyAction="https://www.broxel.com/IwsSPEI/PagosRecibidosParaTercerosResponse")]
        System.Threading.Tasks.Task<BroxelWSCore.wsSPEI.Respuesta> PagosRecibidosParaTercerosAsync(string fecha);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsSPEIChannel : BroxelWSCore.wsSPEI.IwsSPEI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsSPEIClient : System.ServiceModel.ClientBase<BroxelWSCore.wsSPEI.IwsSPEI>, BroxelWSCore.wsSPEI.IwsSPEI {
        
        public IwsSPEIClient() {
        }
        
        public IwsSPEIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsSPEIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsSPEIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsSPEIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BroxelWSCore.wsSPEI.Respuesta registraOrden(int IdDetalleDiario) {
            return base.Channel.registraOrden(IdDetalleDiario);
        }
        
        public System.Threading.Tasks.Task<BroxelWSCore.wsSPEI.Respuesta> registraOrdenAsync(int IdDetalleDiario) {
            return base.Channel.registraOrdenAsync(IdDetalleDiario);
        }
        
        public BroxelWSCore.wsSPEI.RespuestaTransferencia registraTranferencia(BroxelWSCore.wsSPEI.Transferencia transferencia) {
            return base.Channel.registraTranferencia(transferencia);
        }
        
        public System.Threading.Tasks.Task<BroxelWSCore.wsSPEI.RespuestaTransferencia> registraTranferenciaAsync(BroxelWSCore.wsSPEI.Transferencia transferencia) {
            return base.Channel.registraTranferenciaAsync(transferencia);
        }
        
        public BroxelWSCore.wsSPEI.Respuesta PagosRecibidosParaTerceros(string fecha) {
            return base.Channel.PagosRecibidosParaTerceros(fecha);
        }
        
        public System.Threading.Tasks.Task<BroxelWSCore.wsSPEI.Respuesta> PagosRecibidosParaTercerosAsync(string fecha) {
            return base.Channel.PagosRecibidosParaTercerosAsync(fecha);
        }
    }
}
