//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srvBroxel.wsClabe {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoClabe", Namespace="http://schemas.datacontract.org/2004/07/wsClabe")]
    [System.SerializableAttribute()]
    public partial class ResultadoClabe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BancoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClabeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DigitoVerificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorValidacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsBroxelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsValidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdBancoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPlazaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PlazaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Banco {
            get {
                return this.BancoField;
            }
            set {
                if ((object.ReferenceEquals(this.BancoField, value) != true)) {
                    this.BancoField = value;
                    this.RaisePropertyChanged("Banco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clabe {
            get {
                return this.ClabeField;
            }
            set {
                if ((object.ReferenceEquals(this.ClabeField, value) != true)) {
                    this.ClabeField = value;
                    this.RaisePropertyChanged("Clabe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cuenta {
            get {
                return this.CuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.CuentaField, value) != true)) {
                    this.CuentaField = value;
                    this.RaisePropertyChanged("Cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DigitoVerificador {
            get {
                return this.DigitoVerificadorField;
            }
            set {
                if ((this.DigitoVerificadorField.Equals(value) != true)) {
                    this.DigitoVerificadorField = value;
                    this.RaisePropertyChanged("DigitoVerificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorValidacion {
            get {
                return this.ErrorValidacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorValidacionField, value) != true)) {
                    this.ErrorValidacionField = value;
                    this.RaisePropertyChanged("ErrorValidacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsBroxel {
            get {
                return this.EsBroxelField;
            }
            set {
                if ((this.EsBroxelField.Equals(value) != true)) {
                    this.EsBroxelField = value;
                    this.RaisePropertyChanged("EsBroxel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsValida {
            get {
                return this.EsValidaField;
            }
            set {
                if ((this.EsValidaField.Equals(value) != true)) {
                    this.EsValidaField = value;
                    this.RaisePropertyChanged("EsValida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdBanco {
            get {
                return this.IdBancoField;
            }
            set {
                if ((this.IdBancoField.Equals(value) != true)) {
                    this.IdBancoField = value;
                    this.RaisePropertyChanged("IdBanco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPlaza {
            get {
                return this.IdPlazaField;
            }
            set {
                if ((this.IdPlazaField.Equals(value) != true)) {
                    this.IdPlazaField = value;
                    this.RaisePropertyChanged("IdPlaza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Plaza {
            get {
                return this.PlazaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlazaField, value) != true)) {
                    this.PlazaField = value;
                    this.RaisePropertyChanged("Plaza");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsClabe.IWebServiceClabe")]
    public interface IWebServiceClabe {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceClabe/ValidarClabe", ReplyAction="http://tempuri.org/IWebServiceClabe/ValidarClabeResponse")]
        srvBroxel.wsClabe.ResultadoClabe ValidarClabe(string clabe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceClabe/ValidarClabe", ReplyAction="http://tempuri.org/IWebServiceClabe/ValidarClabeResponse")]
        System.Threading.Tasks.Task<srvBroxel.wsClabe.ResultadoClabe> ValidarClabeAsync(string clabe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceClabe/GenerarClabeBroxel", ReplyAction="http://tempuri.org/IWebServiceClabe/GenerarClabeBroxelResponse")]
        srvBroxel.wsClabe.ResultadoClabe GenerarClabeBroxel(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceClabe/GenerarClabeBroxel", ReplyAction="http://tempuri.org/IWebServiceClabe/GenerarClabeBroxelResponse")]
        System.Threading.Tasks.Task<srvBroxel.wsClabe.ResultadoClabe> GenerarClabeBroxelAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceClabe/GenerarClabesMaquila", ReplyAction="http://tempuri.org/IWebServiceClabe/GenerarClabesMaquilaResponse")]
        int GenerarClabesMaquila(string cliente, string producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceClabe/GenerarClabesMaquila", ReplyAction="http://tempuri.org/IWebServiceClabe/GenerarClabesMaquilaResponse")]
        System.Threading.Tasks.Task<int> GenerarClabesMaquilaAsync(string cliente, string producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceClabe/GenerarClabesMaquilaCompleto", ReplyAction="http://tempuri.org/IWebServiceClabe/GenerarClabesMaquilaCompletoResponse")]
        int GenerarClabesMaquilaCompleto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceClabe/GenerarClabesMaquilaCompleto", ReplyAction="http://tempuri.org/IWebServiceClabe/GenerarClabesMaquilaCompletoResponse")]
        System.Threading.Tasks.Task<int> GenerarClabesMaquilaCompletoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebServiceClabeChannel : srvBroxel.wsClabe.IWebServiceClabe, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceClabeClient : System.ServiceModel.ClientBase<srvBroxel.wsClabe.IWebServiceClabe>, srvBroxel.wsClabe.IWebServiceClabe {
        
        public WebServiceClabeClient() {
        }
        
        public WebServiceClabeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceClabeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClabeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClabeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public srvBroxel.wsClabe.ResultadoClabe ValidarClabe(string clabe) {
            return base.Channel.ValidarClabe(clabe);
        }
        
        public System.Threading.Tasks.Task<srvBroxel.wsClabe.ResultadoClabe> ValidarClabeAsync(string clabe) {
            return base.Channel.ValidarClabeAsync(clabe);
        }
        
        public srvBroxel.wsClabe.ResultadoClabe GenerarClabeBroxel(int id) {
            return base.Channel.GenerarClabeBroxel(id);
        }
        
        public System.Threading.Tasks.Task<srvBroxel.wsClabe.ResultadoClabe> GenerarClabeBroxelAsync(int id) {
            return base.Channel.GenerarClabeBroxelAsync(id);
        }
        
        public int GenerarClabesMaquila(string cliente, string producto) {
            return base.Channel.GenerarClabesMaquila(cliente, producto);
        }
        
        public System.Threading.Tasks.Task<int> GenerarClabesMaquilaAsync(string cliente, string producto) {
            return base.Channel.GenerarClabesMaquilaAsync(cliente, producto);
        }
        
        public int GenerarClabesMaquilaCompleto() {
            return base.Channel.GenerarClabesMaquilaCompleto();
        }
        
        public System.Threading.Tasks.Task<int> GenerarClabesMaquilaCompletoAsync() {
            return base.Channel.GenerarClabesMaquilaCompletoAsync();
        }
    }
}
