//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srvBroxel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleClientesBroxel
    {
        public long Id { get; set; }
        public int IdCliente { get; set; }
        public string ClaveCliente { get; set; }
        public string Producto { get; set; }
        public double LineaCreditoOriginal { get; set; }
        public double Dispersado { get; set; }
        public double Abonos { get; set; }
        public double CargosB1010 { get; set; }
        public double TransferenciasB1010 { get; set; }
        public double DevolucionesDeCuentas { get; set; }
        public decimal PagosCredito { get; set; }
        public double LineaCreditoActual { get; set; }
        public int TopeMaximo { get; set; }
        public int TipoRiesgo { get; set; }
        public string CLABE { get; set; }
        public int TipoComisionDisposicion { get; set; }
        public double ComisionDisposicion { get; set; }
        public double ATM { get; set; }
        public bool EnviaPagos { get; set; }
        public bool SmartData { get; set; }
        public bool Conferma { get; set; }
        public bool Activo { get; set; }
        public bool EnviaSMSs { get; set; }
        public bool EncolaDispersiones { get; set; }
        public int TipoComisionTransferencia { get; set; }
        public double ComisionTransferencia { get; set; }
        public int TipoConceptoComisionTransferencia { get; set; }
        public int RecibeTransferencia { get; set; }
        public Nullable<sbyte> Activa_Bloquea { get; set; }
        public Nullable<System.TimeSpan> HoraActivacion { get; set; }
        public Nullable<System.TimeSpan> HoraBloqueo { get; set; }
        public string CuentaConcentradora { get; set; }
        public string EjecutivoComercial { get; set; }
        public decimal FactorDeposito { get; set; }
        public int CambioDeNip { get; set; }
        public string CorreoNotificaciones { get; set; }
        public string SMSNotificacion { get; set; }
        public int DisposicionesSinCobro { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaUsuarioCreacion { get; set; }
        public bool AplicaSPEI { get; set; }
        public bool DesglosaIEPS { get; set; }
    }
}
