//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srvBroxel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCuentasOrdenDeTrabajo
    {
        public long Id { get; set; }
        public Nullable<int> IdOrdenTrabajo { get; set; }
        public string FolioOrdenTrabajo { get; set; }
        public Nullable<int> IdDetalleTarjetasOrdenImport { get; set; }
        public string CodigoDeProducto { get; set; }
        public string CodigoServicio { get; set; }
        public string NombreTarjetahabiente { get; set; }
        public string CalleYNumPuerta { get; set; }
        public string Interior { get; set; }
        public string Localidad { get; set; }
        public string Colonia { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> CodigoEstado { get; set; }
        public Nullable<int> CodigoProvincia { get; set; }
        public string CodigoPostal { get; set; }
        public string TipoDeDocumento { get; set; }
        public string NumeroDeDocumento { get; set; }
        public string GrupoDeLiquidacion { get; set; }
        public string HabilitaCompra { get; set; }
        public string Email { get; set; }
        public Nullable<int> IdMaquila { get; set; }
    }
}
