//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srvBroxel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class maquila
    {
        public int id { get; set; }
        public string nro_corr { get; set; }
        public string nro_tarjeta { get; set; }
        public string nombre_titular { get; set; }
        public string num_cuenta { get; set; }
        public string domicilio { get; set; }
        public string NumeroCalle { get; set; }
        public string piso { get; set; }
        public string localidad { get; set; }
        public string Colonia { get; set; }
        public string codigo_postal { get; set; }
        public string provincia { get; set; }
        public string TipoDomicilio { get; set; }
        public string NumDocumento { get; set; }
        public string TipoDocumento { get; set; }
        public string Telefono { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> FechaDeNacimiento { get; set; }
        public string EstadoCivil { get; set; }
        public string Hijos { get; set; }
        public string Ocupacion { get; set; }
        public string nombre_tarjethabiente { get; set; }
        public Nullable<decimal> limite_compras { get; set; }
        public Nullable<decimal> limite_credito { get; set; }
        public Nullable<decimal> imp_adelantos { get; set; }
        public string grupo_cuenta { get; set; }
        public string producto { get; set; }
        public Nullable<System.DateTime> import { get; set; }
        public string maquila1 { get; set; }
        public Nullable<decimal> saldo_restante { get; set; }
        public Nullable<decimal> total_movimientos { get; set; }
        public Nullable<System.DateTime> fecha_ultimo_movimiento { get; set; }
        public Nullable<decimal> disponible { get; set; }
        public string estado_operativo { get; set; }
        public Nullable<System.DateTime> fecha_disponible { get; set; }
        public Nullable<System.DateTime> fecha_ultima_modificacion { get; set; }
        public string cliente_bx { get; set; }
        public string cuenta_madre { get; set; }
        public string programa { get; set; }
        public string clave_cliente { get; set; }
        public string C4ta_linea { get; set; }
        public Nullable<int> usuario_web { get; set; }
        public string email { get; set; }
        public string referenciaCliente { get; set; }
        public int MesesInactiva { get; set; }
        public string Fondeo { get; set; }
        public string CodigoPostalFiscal { get; set; }
        public string Calle { get; set; }
        public string ColoniaFiscal { get; set; }
        public string EstadoFiscal { get; set; }
        public string LocalidadFiscal { get; set; }
        public string MunicipioFiscal { get; set; }
        public string NumExterior { get; set; }
        public string Estado { get; set; }
        public string NumInterior { get; set; }
        public string NombreCompleto { get; set; }
        public string Pais { get; set; }
        public string RFC { get; set; }
        public string CLABE { get; set; }
        public string CURP { get; set; }
        public string IMSS { get; set; }
        public string DCClaveCliente { get; set; }
        public string DCConsecCliente { get; set; }
        public string CodigoPostalFiscat { get; set; }
        public Nullable<int> IdODTTarj { get; set; }
        public int IdTipoNotificacionSMS { get; set; }
        public Nullable<int> IdNivelDeCuenta { get; set; }
    }
}
