//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARBC
    {
        public int idErrorRespBC { get; set; }
        public int idAR { get; set; }
        public string referenciaOperador { get; set; }
        public string sujetoNoAutenticado { get; set; }
        public string claveOPasswordErroneso { get; set; }
        public string errorSistemaBC { get; set; }
        public string etiquetaSegmentoErronea { get; set; }
        public string faltaCampoRequerido { get; set; }
    
        public virtual ErrorRespBC ErrorRespBC { get; set; }
    }
}
