//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaEfectuadaRespBC
    {
        public int idPersonaRespBC { get; set; }
        public int idConsultaEfectuadaRespBC { get; set; }
        public string fechaConsulta { get; set; }
        public string identificacionBuro { get; set; }
        public string claveOtorgante { get; set; }
        public string nombreOtorgante { get; set; }
        public string telefonoOtorgante { get; set; }
        public string tipoContrato { get; set; }
        public string claveUnidadMonetaria { get; set; }
        public string importeContrato { get; set; }
        public string indicadorTipoResponsabilidad { get; set; }
        public string consumidorNuevo { get; set; }
        public string resultadoFinal { get; set; }
        public string identificadorOrigenConsulta { get; set; }
    
        public virtual PersonaRespBC PersonaRespBC { get; set; }
    }
}
