//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleoBCResp
    {
        public int idPersonaBCResp { get; set; }
        public int idEmpleo { get; set; }
        public string nombreEmpresa { get; set; }
        public string direccion1 { get; set; }
        public string direccion2 { get; set; }
        public string coloniaPoblacion { get; set; }
        public string delegacionMunicipio { get; set; }
        public string ciudad { get; set; }
        public string estado { get; set; }
        public string cp { get; set; }
        public string numeroTelefono { get; set; }
        public string extension { get; set; }
        public string fax { get; set; }
        public string cargo { get; set; }
        public string fechaContratacion { get; set; }
        public string claveMoneda { get; set; }
        public string salario { get; set; }
        public string baseSalarial { get; set; }
        public string fechaUltimoDiaEmpleo { get; set; }
        public string fechaReportoEmpleo { get; set; }
        public string fechaVerificacionEmpleo { get; set; }
        public string modoVerificacion { get; set; }
    
        public virtual PersonaRespBC PersonaRespBC { get; set; }
    }
}
