//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBC
{
    using System;
    using System.Collections.Generic;
    
    public partial class HawkAlertConsultaRespBC
    {
        public int idPersonaRespBC { get; set; }
        public int idHawkAlertConsultaRespC { get; set; }
        public string fechaReporte { get; set; }
        public string codigoClave { get; set; }
        public string tipoInstitucion { get; set; }
        public string mensaje { get; set; }
    
        public virtual PersonaRespBC PersonaRespBC { get; set; }
    }
}
