//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MensajeBCResp
    {
        public int idConsultaBC { get; set; }
        public int idMensajeResp { get; set; }
        public string tipoMensaje { get; set; }
        public string leyenda { get; set; }
    
        public virtual ConsultaBC ConsultaBC { get; set; }
    }
}
