//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBC
{
    using System;
    using System.Collections.Generic;
    
    public partial class NombreBCResp
    {
        public int idPersonaBCResp { get; set; }
        public int idNombreResp { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string apellidoAdicional { get; set; }
        public string primerNombre { get; set; }
        public string segundoNombre { get; set; }
        public string fechaNacimiento { get; set; }
        public string rfc { get; set; }
        public string prefijo { get; set; }
        public string sufijo { get; set; }
        public string nacionalidad { get; set; }
        public string residencia { get; set; }
        public string estadoCivil { get; set; }
        public string sexo { get; set; }
        public string numeroCedulaProfesional { get; set; }
        public string numeroRegistroElectoral { get; set; }
        public string claveImpuestosOtroPais { get; set; }
        public string claveOtroPais { get; set; }
        public string numeroDependientes { get; set; }
        public string edadesDependientes { get; set; }
        public string fechaDefuncion { get; set; }
        public string fechaRecepciónInformacionDependientes { get; set; }
    
        public virtual PersonaRespBC PersonaRespBC { get; set; }
    }
}
