//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBC
{
    using System;
    using System.Collections.Generic;
    
    public partial class URBC
    {
        public int idErrorRespBC { get; set; }
        public int idURBC { get; set; }
        public string numeroReferenciaOperador { get; set; }
        public string solicitudClienteErronea { get; set; }
        public string versionProporcionadaErronea { get; set; }
        public string productoSolicitadoErroneo { get; set; }
        public string passwordOClaveErronea { get; set; }
        public string segmentoRequerido { get; set; }
        public string ultimaInformacionValidaCliente { get; set; }
        public string informacionErroneaParaConsulta { get; set; }
        public string valorErroneoCampoRelacionado { get; set; }
        public string errorSistemaBuroCredito { get; set; }
        public string etiquetaSegmentoErronea { get; set; }
        public string ordenErroneoSegmento { get; set; }
        public string numeroErroneoSegmentos { get; set; }
        public string faltaCampoRequerido { get; set; }
        public string errorReporteBloqueado { get; set; }
    
        public virtual ErrorRespBC ErrorRespBC { get; set; }
    }
}
