//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suncorp.Models
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class OpeZonasPorEstados{
    	[DataMember]	
        public int IdZonasEstados { get; set; }
    	[DataMember]	
        public Nullable<short> IdEstado { get; set; }
    	[DataMember]	
        public Nullable<short> IdZona { get; set; }
    	[DataMember]	
        public Nullable<bool> Borrado { get; set; }
    
        public virtual DirCatEstados DirCatEstados { get; set; }
        public virtual OpeCatZonas OpeCatZonas { get; set; }
    }
}
