//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroxelWSCore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class broxelco_rdgEntities : DbContext
    {
        public broxelco_rdgEntities()
            : base("name=broxelco_rdgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accessos_clientes> accessos_clientes { get; set; }
        public virtual DbSet<bancos_stp> bancos_stp { get; set; }
        public virtual DbSet<CargosDisposicionesEfectivo> CargosDisposicionesEfectivo { get; set; }
        public virtual DbSet<cat_incremento> cat_incremento { get; set; }
        public virtual DbSet<catalogo_acceso_comercios> catalogo_acceso_comercios { get; set; }
        public virtual DbSet<clientesBroxel> clientesBroxel { get; set; }
        public virtual DbSet<ClientesComisiones> ClientesComisiones { get; set; }
        public virtual DbSet<Comercio> Comercio { get; set; }
        public virtual DbSet<ComisionesB1010> ComisionesB1010 { get; set; }
        public virtual DbSet<correr_disponibles> correr_disponibles { get; set; }
        public virtual DbSet<cuentastmp> cuentastmp { get; set; }
        public virtual DbSet<DetalleClientesBroxel> DetalleClientesBroxel { get; set; }
        public virtual DbSet<devolucionesInternas> devolucionesInternas { get; set; }
        public virtual DbSet<devolucionesSolicitudes> devolucionesSolicitudes { get; set; }
        public virtual DbSet<dispersionesInternas> dispersionesInternas { get; set; }
        public virtual DbSet<dispersionesSolicitudes> dispersionesSolicitudes { get; set; }
        public virtual DbSet<dispersionesWE> dispersionesWE { get; set; }
        public virtual DbSet<disponibles> disponibles { get; set; }
        public virtual DbSet<DisposicionesEfectivo> DisposicionesEfectivo { get; set; }
        public virtual DbSet<dispositivos> dispositivos { get; set; }
        public virtual DbSet<estadosCredencial> estadosCredencial { get; set; }
        public virtual DbSet<fechas_corte_x_grupos> fechas_corte_x_grupos { get; set; }
        public virtual DbSet<HistoricoComisionesPublidea> HistoricoComisionesPublidea { get; set; }
        public virtual DbSet<ind_movimientos> ind_movimientos { get; set; }
        public virtual DbSet<log_registro_de_cuenta> log_registro_de_cuenta { get; set; }
        public virtual DbSet<LogActividadesOperaciones> LogActividadesOperaciones { get; set; }
        public virtual DbSet<LogUsuariosOnlineBroxel> LogUsuariosOnlineBroxel { get; set; }
        public virtual DbSet<MailConfig> MailConfig { get; set; }
        public virtual DbSet<MailingThemesOnline> MailingThemesOnline { get; set; }
        public virtual DbSet<maquila> maquila { get; set; }
        public virtual DbSet<Monedas> Monedas { get; set; }
        public virtual DbSet<MovimientosClientes> MovimientosClientes { get; set; }
        public virtual DbSet<OnLineFavoritos> OnLineFavoritos { get; set; }
        public virtual DbSet<OrdenDeTrabajo> OrdenDeTrabajo { get; set; }
        public virtual DbSet<pagosInternos> pagosInternos { get; set; }
        public virtual DbSet<pagosSolicitudes> pagosSolicitudes { get; set; }
        public virtual DbSet<phpSession> phpSession { get; set; }
        public virtual DbSet<productos_broxel> productos_broxel { get; set; }
        public virtual DbSet<registri_broxel> registri_broxel { get; set; }
        public virtual DbSet<registro_de_cuenta> registro_de_cuenta { get; set; }
        public virtual DbSet<registro_tc> registro_tc { get; set; }
        public virtual DbSet<RenominacionesInternas> RenominacionesInternas { get; set; }
        public virtual DbSet<RenominacionSolicitudes> RenominacionSolicitudes { get; set; }
        public virtual DbSet<reversos> reversos { get; set; }
        public virtual DbSet<session_dash> session_dash { get; set; }
        public virtual DbSet<Transferencias> Transferencias { get; set; }
        public virtual DbSet<TransferenciasDetalle> TransferenciasDetalle { get; set; }
        public virtual DbSet<TransferenciasSolicitud> TransferenciasSolicitud { get; set; }
        public virtual DbSet<UsuariosOnlineBroxel> UsuariosOnlineBroxel { get; set; }
        public virtual DbSet<UsuariosOnlineCLABE> UsuariosOnlineCLABE { get; set; }
        public virtual DbSet<CodigosRespuesta> CodigosRespuesta { get; set; }
        public virtual DbSet<vw_EdoCuenta> vw_EdoCuenta { get; set; }
        public virtual DbSet<vw_maquila> vw_maquila { get; set; }
        public virtual DbSet<vw_registri> vw_registri { get; set; }
        public virtual DbSet<vw_registri_broxel> vw_registri_broxel { get; set; }
    }
}
