//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroxelWSCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_broxel
    {
        public int ID0 { get; set; }
        public Nullable<int> id { get; set; }
        public string codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> tipodaldo { get; set; }
        public string mensaje1 { get; set; }
        public string mensaje2 { get; set; }
        public string branding { get; set; }
        public string mensaje3 { get; set; }
        public string tipo { get; set; }
        public Nullable<sbyte> dispersa { get; set; }
        public int DisposicionEfectivo { get; set; }
        public double ComisionDisposicion { get; set; }
        public bool PagoEnLinea { get; set; }
        public Nullable<float> PorcentajeDisposicion { get; set; }
        public Nullable<int> Bin { get; set; }
        public string Programa { get; set; }
        public string DescripcionProducto { get; set; }
        public string SegurosAsistencia { get; set; }
        public string Caracteristicas { get; set; }
        public string CodigoAfinidad { get; set; }
        public Nullable<bool> SmartData { get; set; }
        public int TipoComisionTransferencia { get; set; }
        public double ComisionTransferencia { get; set; }
        public int TipoConceptoComisionTransferencia { get; set; }
        public int RecibeTransferencia { get; set; }
        public Nullable<int> TipoMedidasMaquila { get; set; }
        public int CambioDeNip { get; set; }
        public bool IncluirRedDePagos { get; set; }
    }
}
