//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroxelWSCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenominacionesInternas
    {
        public long Id { get; set; }
        public long IdSolicitud { get; set; }
        public string FolioSolicitud { get; set; }
        public string Cuenta { get; set; }
        public string Tarjeta { get; set; }
        public string CodigoRespuesta { get; set; }
        public string CodigoAutorizacion { get; set; }
        public long IdRenominacion { get; set; }
        public string Producto { get; set; }
        public string ClaveCliente { get; set; }
        public string NombreCalle { get; set; }
        public string NumeroCalle { get; set; }
        public string Colonia { get; set; }
        public string CodigoPostal { get; set; }
        public string NombreMunicipio { get; set; }
        public string TipoDireccion { get; set; }
        public string CodigoEstado { get; set; }
        public string CodigoMunicipio { get; set; }
        public string Pais { get; set; }
        public string NumeroDeDocumento { get; set; }
        public string TipoDocumento { get; set; }
        public string GrupoLiquidacion { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string EstadoCivil { get; set; }
        public string Hijos { get; set; }
        public string Sexo { get; set; }
        public string Ocupacion { get; set; }
        public string DenominacionTarjeta { get; set; }
        public string NombreCompletoTitular { get; set; }
    }
}
