//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOB.SPF.ConecII.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MethodApiContraprestacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MethodApiContraprestacion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GOB.SPF.ConecII.Web.Resources.MethodApiContraprestacion", typeof(MethodApiContraprestacion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cetes/Cargar.
        /// </summary>
        internal static string CetesGuardar {
            get {
                return ResourceManager.GetString("CetesGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cetes/ObtenerPorCriterio.
        /// </summary>
        internal static string CetesObtenerPorCriterio {
            get {
                return ResourceManager.GetString("CetesObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cetes/Previsualizar.
        /// </summary>
        internal static string CetesPrevisualizar {
            get {
                return ResourceManager.GetString("CetesPrevisualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterosTesofe/Cargar.
        /// </summary>
        internal static string TesofeGuardar {
            get {
                return ResourceManager.GetString("TesofeGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterosTesofe/ObtenerPorCriterio.
        /// </summary>
        internal static string TesofeObtenerPorCriterio {
            get {
                return ResourceManager.GetString("TesofeObtenerPorCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterosTesofe/Previsualizar.
        /// </summary>
        internal static string TesofePrevisualizar {
            get {
                return ResourceManager.GetString("TesofePrevisualizar", resourceCulture);
            }
        }
    }
}
