SELECT 
	O.EXTERNAL_ID
FROM 
    IAC_PAYMENT_MEDIA IPM
    INNER JOIN  ICS_PAYMENT_MEDIA_RELATION IPMR ON IPM.ID_PAYMENT_MEDIA = IPMR.ID_PAYMENT_MEDIA
	INNER JOIN  ICS_ACCOUNT_RELATION IAR ON IPMR.ID_ACCOUNT_RELATION  = IAR.ID_ACCOUNT_RELATION
	INNER JOIN  ICS_FINANCIAL_RELATION IFR ON IAR.ID_FINANCIAL_RELATION = IFR.ID_FINANCIAL_RELATION
	INNER JOIN  IAC_GENERAL_ACCOUNT IAC ON IAC.ID_GENERAL_ACCOUNT = IFR.ID_GENERAL_ACCOUNT
	INNER JOIN  IBC_PAYMENT_MEDIA_STATUS PME ON IPM.ID_PAYMENT_MEDIA_STATUS = PME.ID_PAYMENT_MEDIA_STATUS
	INNER JOIN  IBC_AFFINITY_GROUP AG ON  AG.ID_AFFINITY_GROUP  =  IAR.ID_AFFINITY_GROUP
	INNER JOIN  IBC_ISSUER ISS ON  ISS.ID_ISSUER = IPM.ID_ISSUER
	INNER JOIN  C_ORGANIZATION O ON  ISS.id_organization = o.id_organization
	INNER JOIN  ICS_CUSTOMER ICC ON IFR.ID_CUSTOMER = ICC.ID_CUSTOMER
    
WHERE
    IAC.INTERNAL_ACCOUNT_NUMBER = '0000039611' and  
     PME.Description NOT LIKE '%cancel%'         
ORDER BY 
    IPM.ID_PAYMENT_MEDIA ASC